### ISSUE TITLE
Errors at end of pipeline

### ISSUE THREAD

**Issue by jaflynn5** [ENCODE-DCC/chip-seq-pipeline2#135]
**Describe the bug**
I was able to run the ECODE chip seq pipeline on my own dataset starting from adapter-trimmed fastq.gz files. However, near the end of the pipeline I encountered a few errors which I am having trouble interpreting. 

**OS/Platform**
- OS/Platform: Ubuntu 16.04
- Conda version: 4.7.12
- Pipeline version: 1.3.6
- Caper version: 0.6.4

**Caper configuration file**
backend=local

# DO NOT use /tmp here
# Caper stores all important temp files and cached big data files here
tmp-dir=./intermediate_caper_files

**Input JSON file**
{
    "chip.pipeline_type" : "tf",
    "chip.genome_tsv" : "https://storage.googleapis.com/encode-pipeline-genome-data/genome_tsv/v1/hg19_caper.tsv",
    "chip.fastqs_rep1_R1" : ["https://wangftp.wustl.edu/~jflynn/H1299/adapter_trimmed_fastq_files_reps_1_through_4/WangT_ChIP-JF_GTACIndex1_TGAGGTTATC_AGATCTCG_S5_R1_001.fastq_trim.gz"],
    "chip.fastqs_rep1_R2" : ["https://wangftp.wustl.edu/~jflynn/H1299/adapter_trimmed_fastq_files_reps_1_through_4/WangT_ChIP-JF_GTACIndex1_TGAGGTTATC_AGATCTCG_S5_R2_001.fastq_trim.gz"],
    "chip.fastqs_rep2_R1" : ["https://wangftp.wustl.edu/~jflynn/H1299/adapter_trimmed_fastq_files_reps_1_through_4/WangT_ChIP-EZH2-Rep-2_GTAC-Index3_ATGACAGATC_S12_R1_001.fastq_trim.gz"],
    "chip.fastqs_rep2_R2" : ["https://wangftp.wustl.edu/~jflynn/H1299/adapter_trimmed_fastq_files_reps_1_through_4/WangT_ChIP-EZH2-Rep-2_GTAC-Index3_ATGACAGATC_S12_R2_001.fastq.gz"],
    "chip.fastqs_rep3_R1" : ["https://wangftp.wustl.edu/~jflynn/H1299/adapter_trimmed_fastq_files_reps_1_through_4/WangT_Jen-EZH2R1_GTACIndex2_GCTTAGAATC_S6_R1_001.fastq_trim.gz"],
    "chip.fastqs_rep3_R2" : ["https://wangftp.wustl.edu/~jflynn/H1299/adapter_trimmed_fastq_files_reps_1_through_4/WangT_Jen-EZH2R1_GTACIndex2_GCTTAGAATC_S6_R2_001.fastq_trim.gz"],
    "chip.fastqs_rep4_R1" : ["https://wangftp.wustl.edu/~jflynn/H1299/adapter_trimmed_fastq_files_reps_1_through_4/WangT_Jen-EZH2R2_GTACIndex5_ATCGAGCATC_S8_R1_001.fastq_trim.gz"],
    "chip.fastqs_rep4_R2" : ["https://wangftp.wustl.edu/~jflynn/H1299/adapter_trimmed_fastq_files_reps_1_through_4/WangT_Jen-EZH2R2_GTACIndex5_ATCGAGCATC_S8_R2_001.fastq_trim.gz"],
    "chip.ctl_fastqs_rep1_R1" : ["https://wangftp.wustl.edu/~jflynn/H1299/adapter_trimmed_fastq_files_reps_1_through_4/WangT_ChIP_ChIP-input_GTAC_Index45_GATAGTTATC_S4_R1_001.fastq_trim.gz"],
    "chip.ctl_fastqs_rep1_R2" : ["https://wangftp.wustl.edu/~jflynn/H1299/adapter_trimmed_fastq_files_reps_1_through_4/WangT_ChIP_ChIP-input_GTAC_Index45_GATAGTTATC_S4_R2_001.fastq_trim.gz"],
    "chip.ctl_fastqs_rep2_R1" : ["https://wangftp.wustl.edu/~jflynn/H1299/adapter_trimmed_fastq_files_reps_1_through_4/WangT_ChIP-Input-Rep-2_GTAC-Index2_GCTTAGAATC_S10_R1_001.fastq_trim.gz"],
    "chip.ctl_fastqs_rep2_R2" : ["https://wangftp.wustl.edu/~jflynn/H1299/adapter_trimmed_fastq_files_reps_1_through_4/WangT_ChIP-Input-Rep-2_GTAC-Index2_GCTTAGAATC_S10_R2_001.fastq_trim.gz"],
    "chip.ctl_fastqs_rep3_R1" : ["https://wangftp.wustl.edu/~jflynn/H1299/adapter_trimmed_fastq_files_reps_1_through_4/WangT_Jen-InputR1_GTACIndex4_CACCTCCATC_S7_R1_001.fastq_trim.gz"],
    "chip.ctl_fastqs_rep3_R2" : ["https://wangftp.wustl.edu/~jflynn/H1299/adapter_trimmed_fastq_files_reps_1_through_4/WangT_Jen-InputR1_GTACIndex4_CACCTCCATC_S7_R2_001.fastq_trim.gz"],
    "chip.ctl_fastqs_rep4_R1" : ["https://wangftp.wustl.edu/~jflynn/H1299/adapter_trimmed_fastq_files_reps_1_through_4/WangT_Jen-InputR2_GTACIndex6_TACTCTAATC_S9_R1_001.fastq_trim.gz"],
    "chip.ctl_fastqs_rep4_R2" : ["https://wangftp.wustl.edu/~jflynn/H1299/adapter_trimmed_fastq_files_reps_1_through_4/WangT_Jen-InputR2_GTACIndex6_TACTCTAATC_S9_R2_001.fastq_trim.gz"],
    "chip.paired_end" : true,
    "chip.ctl_paired_end" : true,
    "chip.title" : "EZH2 in H1299 Reps 1-4",
    "chip.description" : "EZH2 ChIP-seq on H1299 for Replicates 1-4"
}
**Error log**
[Caper] troubleshooting 2d9dd1b7-c037-44f7-937b-3687b81eb5c7 ...
Found failures:
[
    {
        "causedBy": [
            {
                "causedBy": [],
                "message": "Job chip.idr:2:2 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details."
            }
        ],
        "message": "Workflow failed"
    }
]

chip.idr RetryableFailure. SHARD_IDX=2, RC=1, JOB_ID=40041, RUN_START=2020-03-05T07:16:51.118Z, RUN_END=2020-03-05T07:20:36.014Z, STDOUT=/tavern/jflynn/Projects/metastasis/ChIP_seq_EZH2_H1299/calculate_cross_correlation/my_data/chip/2d9dd1b7-c037-44f7-937b-3687b81eb5c7/call-idr/shard-2/execution/stdout, STDERR=/tavern/jflynn/Projects/metastasis/ChIP_seq_EZH2_H1299/calculate_cross_correlation/my_data/chip/2d9dd1b7-c037-44f7-937b-3687b81eb5c7/call-idr/shard-2/execution/stderr
STDERR_CONTENTS=
Traceback (most recent call last):
  File "/bar/jflynn/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_task_idr.py", line 182, in <module>
    main()
  File "/bar/jflynn/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_task_idr.py", line 157, in main
    idr_peak, args.blacklist, args.regex_bfilt_peak_chr_name, args.out_dir)
  File "/bar/jflynn/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_lib_blacklist_filter.py", line 72, in blacklist_filter
    run_shell_cmd(cmd)
  File "/bar/jflynn/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_lib_common.py", line 319, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=42464, PGID=42464, RC=1
STDERR=
STDOUT=

chip.idr Failed. SHARD_IDX=2, RC=1, JOB_ID=42534, RUN_START=2020-03-05T07:20:37.008Z, RUN_END=2020-03-05T07:23:24.421Z, STDOUT=/tavern/jflynn/Projects/metastasis/ChIP_seq_EZH2_H1299/calculate_cross_correlation/my_data/chip/2d9dd1b7-c037-44f7-937b-3687b81eb5c7/call-idr/shard-2/attempt-2/execution/stdout, STDERR=/tavern/jflynn/Projects/metastasis/ChIP_seq_EZH2_H1299/calculate_cross_correlation/my_data/chip/2d9dd1b7-c037-44f7-937b-3687b81eb5c7/call-idr/shard-2/attempt-2/execution/stderr
STDERR_CONTENTS=
Traceback (most recent call last):
  File "/bar/jflynn/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_task_idr.py", line 182, in <module>
    main()
  File "/bar/jflynn/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_task_idr.py", line 157, in main
    idr_peak, args.blacklist, args.regex_bfilt_peak_chr_name, args.out_dir)
  File "/bar/jflynn/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_lib_blacklist_filter.py", line 72, in blacklist_filter
    run_shell_cmd(cmd)
  File "/bar/jflynn/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_lib_common.py", line 319, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=42623, PGID=42623, RC=1
STDERR=
STDOUT=

**Comment by leepc12** [comment]
Increase your IDR threshold than default then try again.

**Comment by jaflynn5** [comment]
Do I need to re-run the entire pipeline again (starting with adapter-trimmed fastq.gz files)? Or can I pick up somewhere in the middle/towards the end of the pipeline?
________________________________

**Comment by leepc12** [comment]
If you have set up database `--db` correctly. then pipeline will collect outputs from previous runs. Or you can manually start from BAM, filtered BAM, TAG-ALIGNs.

**Comment by jaflynn5** [comment]
Thank you! Could you also please inform me as to how I can increase the IDR threshold? I do not see where this parameter is customizable.

**Comment by leepc12** [comment]
Increase it to an unreasonably high value like 0.5 and see what happens. It's just for testing. If you see something like `(Call-cached)` in the log, that means re-using outputs are working.

**Comment by jaflynn5** [comment]
Hmm, it appears to be starting over with alignment when I re-ran the command (after updating the idr value in the json): 
<code>caper run ../chip-seq-pipeline2/chip.wdl -i ../input_json.json</code>

**Comment by leepc12** [comment]
Please see Caper's documentation about metadata DB and how that is automatically generated if users didn't define it explicitly.

**Comment by jaflynn5** [comment]
I see, so in order to pick up in the middle of the pipeline (use previously generated files) I would have needed to first add <code>--db mysql</code> to my json. I have already re-started the pipeline using the command listed above. If I kill this now and update the json to include <code>--db mysql</code>, will anything be "broken"? Not sure if re-starting the pipeline has caused some intermediate files to change. (I'd like to resume in the middle of the pipeline if possible, since it takes ~2 days to run on our servers).

**Comment by leepc12** [comment]
`db=file` (file-based DB) is okay for most use cases. It is hard to install/configure MySQL.

**Comment by jaflynn5** [comment]
Can I kill the current re-run and use the db=file referring to the previous failed run? Are there intermediate files that would have changed since I started re-running it as above?

**Comment by leepc12** [comment]
To re-use outputs, your previous pipelines should be ran with a metadata DB `db=file` or `db=mysql`. And location of the DB file/server(MySQL) should match (`db-file` or `mysql-db-port`, ...).

**Comment by jaflynn5** [comment]
I am now getting errors such as this (although the pipeline is still running):

2020-03-06 08:31:14,456 cromwell-system-akka.actor.default-dispatcher-184 ERROR - KvWriteActor Failed to properly process data
cromwell.core.CromwellFatalException: java.sql.SQLDataException: data exception: string data, right truncation;  table: JOB_KEY_VALUE_ENTRY column: STORE_VALUE
	at cromwell.core.retry.Retry$$anonfun$withRetry$1.applyOrElse(Retry.scala:47)
	at cromwell.core.retry.Retry$$anonfun$withRetry$1.applyOrElse(Retry.scala:38)
	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:417)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.sql.SQLDataException: data exception: string data, right truncation;  table: JOB_KEY_VALUE_ENTRY column: STORE_VALUE
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.executeUpdate(Unknown Source)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$SingleInsertAction.$anonfun$run$11(JdbcActionComponent.scala:510)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedInsertStatement(JdbcBackend.scala:393)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedInsertStatement$(JdbcBackend.scala:390)
	at slick.jdbc.JdbcBackend$BaseSession.withPreparedInsertStatement(JdbcBackend.scala:448)
	at slick.jdbc.JdbcActionComponent$ReturningInsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:650)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$SingleInsertAction.run(JdbcActionComponent.scala:507)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:30)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:27)
	at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:275)
	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:275)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.hsqldb.HsqlException: data exception: string data, right truncation;  table: JOB_KEY_VALUE_ENTRY column: STORE_VALUE
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.Table.enforceTypeLimits(Unknown Source)
	at org.hsqldb.Table.generateAndCheckData(Unknown Source)
	at org.hsqldb.Table.insertSingleRow(Unknown Source)
	at org.hsqldb.StatementDML.insertRowSet(Unknown Source)
	at org.hsqldb.StatementInsert.getResult(Unknown Source)
	at org.hsqldb.StatementDMQL.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 17 common frames omitted
Caused by: org.hsqldb.HsqlException: data exception: string data, right truncation
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.types.CharacterType.convertToTypeLimits(Unknown Source)
	... 25 common frames omitted

**Comment by leepc12** [comment]
What was your command line (or conf file `~/.caper/default.conf`) for DB settings?

**Comment by jaflynn5** [comment]
command: <code>caper run ../chip-seq-pipeline2/chip.wdl -i ../input_json.json</code>

<code>~./caper/default.conf</code>: 
backend=local
tmp-dir=./intermediate_caper_files

**Comment by leepc12** [comment]
I think you are still using `in-memory` (default) for `--db` since you didn't specify anything about metadata DB.

Define `db=file` in your Conf first. Then Caper (`caper run`) will automatically create metadata DB on your output directory (defined with `--out-dir` or CWD where you ran it).

**Comment by jaflynn5** [comment]
Thank you for your patients as I trouble-shoot this.
Since the pipeline is still running, should I kill if first, define <code>db=file</code> in my conf and then rerun with the same command? (<code>caper run ../chip-seq-pipeline2/chip.wdl -i ../input_json.json</code>)?

**Comment by leepc12** [comment]
Yes.

**Comment by jaflynn5** [comment]
Hi, the pipeline finished. When I went to organize the output (croo [METADATA JSON]); however, I got the error "ModuleNotFoundError: No module named 'graphviz'". On the documentation page (https://github.com/ENCODE-DCC/chip-seq-pipeline2), it says that if I have installed pipeline's Conda environment and activated it (and I have), I should not need to install anything. Do you know why I'm getting this error?

**Comment by leepc12** [comment]
`--no-graph` To Croo command line (you will not get a task graph on HTML report) or install graphviz with the following commands:
```
$ pip install graphviz
$ sudo apt-get install graphviz  # to get an executable called "dot"
```

**Comment by leepc12** [comment]
Closing due to long inactivity.
