### ISSUE TITLE
chip.align and chip.align_R1 tasks fail if input FASTQ(s) cannot be hard-linked

### ISSUE THREAD

**Issue by rivison** [ENCODE-DCC/chip-seq-pipeline2#159]
**Describe the bug**
I've included 2 JSON files below. The first is an example of a run that completed successfully, and the second is an example that failed. All my workflows matching the first succeeded, and all those matching the second failed. The pattern is that all (and only) the failing ones have `"chip.paired_end": true` and a non-empty `"chip.fastqs_rep1_R2"`. 

**OS/Platform**
- OS/Platform: `SYS_TYPE=redhat_7_x86_64` `ARC=lx-amd64`
- Singularity version: 3.5.3-1.1.el7
- Pipeline version: v1.3.6
- Caper version: 0.7.0

**Caper configuration file**
```
backend=Local

tmp-dir=/path/to/tmpdir

cromwell=/path/to/software/caper-0.7.0/lib/cromwell-47.jar
womtool=/path/to/software/caper-0.7.0/lib/womtool-47.jar
```

**Input JSON file**
JSON for succeeding workflow:
```json
{
  "chip.title": "H3K4me1_sample2",
  "chip.description": "H3K4me1 ChIP-Seq on sample2",
  "chip.pipeline_type": "histone",
  "chip.true_rep_only": true,
  "chip.aligner": "bwa",
  "chip.genome_tsv": "/path/to/hg19/encode-dcc/genome.tsv",
  "chip.paired_end": false,
  "chip.fastqs_rep1_R1": [
    "/path/to/data/ChIP-Seq/H3K4me1/sample2/reads.1.fastq.gz"
  ],
  "chip.fastqs_rep1_R2": [],
  "chip.ctl_paired_end": false,
  "chip.ctl_fastqs_rep1_R1": [
    "/path/to/data/ChIP-Seq/H3K4me1/sample2/ctl.1.reads.1.fastq.gz"
  ],
  "chip.ctl_fastqs_rep1_R2": []
}
```

JSON for failing workflow:
```json
{
  "chip.title": "H3K4me1_sample3",
  "chip.description": "H3K4me1 ChIP-Seq on sample3",
  "chip.pipeline_type": "histone",
  "chip.true_rep_only": true,
  "chip.aligner": "bwa",
  "chip.genome_tsv": "/path/to/hg19/encode-dcc/genome.tsv",
  "chip.paired_end": true,
  "chip.fastqs_rep1_R1": [
    "/path/to/data/ChIP-Seq/H3K4me1/sample3/mate1s.1.fastq.gz"
  ],
  "chip.fastqs_rep1_R2": [
    "/path/to/data/ChIP-Seq/H3K4me1/sample3/mate2s.1.fastq.gz"
  ],
  "chip.ctl_paired_end": false,
  "chip.ctl_fastqs_rep1_R1": [
    "/path/to/data/ChIP-Seq/H3K4me1/sample3/ctl.1.reads.1.fastq.gz"
  ],
  "chip.ctl_fastqs_rep1_R2": []
}
```

**Error log**
Output of `caper debug /path/to/data/ChIP-Seq/H3K4me1/sample3/tmp/chip-1.3.6/4b3f9fc8-4dbe-42d7-9332-a02f38e26084/metadata.json`:
```log
[Caper] troubleshooting 4b3f9fc8-4dbe-42d7-9332-a02f38e26084 ...
Found failures:
[
    {
        "causedBy": [
            {
                "causedBy": [],
                "message": "Job chip.align_R1:0:2 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details."
            },
            {
                "causedBy": [],
                "message": "Job chip.align:0:2 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details."
            }
        ],
        "message": "Workflow failed"
    }
]

chip.align RetryableFailure. SHARD_IDX=0, RC=1, JOB_ID=5212, RUN_START=2020-06-02T16:33:06.275Z, RUN_END=2020-06-02T16:36:11.761Z, STDOUT=/path/to/data/ChIP-Seq/H3K4me1/sample3/tmp/chip/4b3f9fc8-4dbe-42d7-9332-a02f38e26084/call-align/shard-0/execution/stdout, STDERR=/path/to/data/ChIP-Seq/H3K4me1/sample3/tmp/chip/4b3f9fc8-4dbe-42d7-9332-a02f38e26084/call-align/shard-0/execution/stderr
STDERR_CONTENTS=
Traceback (most recent call last):
  File "/software/chip-seq-pipeline/src/encode_task_merge_fastq.py", line 105, in <module>
    main()
  File "/software/chip-seq-pipeline/src/encode_task_merge_fastq.py", line 93, in main
    merged_R1 = merge_fastqs(fastqs_R1, 'R1', args.out_dir)
  File "/software/chip-seq-pipeline/src/encode_task_merge_fastq.py", line 72, in merge_fastqs
    run_shell_cmd(cmd)
  File "/software/chip-seq-pipeline/src/encode_lib_common.py", line 319, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=5572, PGID=5572, RC=1
STDERR=gzip: /path/to/data/ChIP-Seq/H3K4me1/sample3/tmp/chip/4b3f9fc8-4dbe-42d7-9332-a02f38e26084/call-align/shard-0/inputs/-889636323/mate1s.1.fastq.gz: No such file or directory
STDOUT=


chip.align Failed. SHARD_IDX=0, RC=1, JOB_ID=9394, RUN_START=2020-06-02T16:36:12.257Z, RUN_END=2020-06-02T16:38:17.034Z, STDOUT=/path/to/data/ChIP-Seq/H3K4me1/sample3/tmp/chip/4b3f9fc8-4dbe-42d7-9332-a02f38e26084/call-align/shard-0/attempt-2/execution/stdout, STDERR=/path/to/data/ChIP-Seq/H3K4me1/sample3/tmp/chip/4b3f9fc8-4dbe-42d7-9332-a02f38e26084/call-align/shard-0/attempt-2/execution/stderr
STDERR_CONTENTS=
Traceback (most recent call last):
  File "/software/chip-seq-pipeline/src/encode_task_merge_fastq.py", line 105, in <module>
    main()
  File "/software/chip-seq-pipeline/src/encode_task_merge_fastq.py", line 93, in main
    merged_R1 = merge_fastqs(fastqs_R1, 'R1', args.out_dir)
  File "/software/chip-seq-pipeline/src/encode_task_merge_fastq.py", line 72, in merge_fastqs
    run_shell_cmd(cmd)
  File "/software/chip-seq-pipeline/src/encode_lib_common.py", line 319, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=10774, PGID=10774, RC=1
STDERR=gzip: /path/to/data/ChIP-Seq/H3K4me1/sample3/tmp/chip/4b3f9fc8-4dbe-42d7-9332-a02f38e26084/call-align/shard-0/attempt-2/inputs/-889636323/mate1s.1.fastq.gz: No such file or directory
STDOUT=


chip.align_R1 RetryableFailure. SHARD_IDX=0, RC=1, JOB_ID=7312, RUN_START=2020-06-02T16:33:10.335Z, RUN_END=2020-06-02T16:35:41.037Z, STDOUT=/path/to/data/ChIP-Seq/H3K4me1/sample3/tmp/chip/4b3f9fc8-4dbe-42d7-9332-a02f38e26084/call-align_R1/shard-0/execution/stdout, STDERR=/path/to/data/ChIP-Seq/H3K4me1/sample3/tmp/chip/4b3f9fc8-4dbe-42d7-9332-a02f38e26084/call-align_R1/shard-0/execution/stderr
STDERR_CONTENTS=
Traceback (most recent call last):
  File "/software/chip-seq-pipeline/src/encode_task_merge_fastq.py", line 105, in <module>
    main()
  File "/software/chip-seq-pipeline/src/encode_task_merge_fastq.py", line 93, in main
    merged_R1 = merge_fastqs(fastqs_R1, 'R1', args.out_dir)
  File "/software/chip-seq-pipeline/src/encode_task_merge_fastq.py", line 72, in merge_fastqs
    run_shell_cmd(cmd)
  File "/software/chip-seq-pipeline/src/encode_lib_common.py", line 319, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=8545, PGID=8545, RC=1
STDERR=gzip: /path/to/data/ChIP-Seq/H3K4me1/sample3/tmp/chip/4b3f9fc8-4dbe-42d7-9332-a02f38e26084/call-align_R1/shard-0/inputs/-889636323/mate1s.1.fastq.gz: No such file or directory
STDOUT=


chip.align_R1 Failed. SHARD_IDX=0, RC=1, JOB_ID=24792, RUN_START=2020-06-02T16:35:42.261Z, RUN_END=2020-06-02T16:37:39.880Z, STDOUT=/path/to/data/ChIP-Seq/H3K4me1/sample3/tmp/chip/4b3f9fc8-4dbe-42d7-9332-a02f38e26084/call-align_R1/shard-0/attempt-2/execution/stdout, STDERR=/path/to/data/ChIP-Seq/H3K4me1/sample3/tmp/chip/4b3f9fc8-4dbe-42d7-9332-a02f38e26084/call-align_R1/shard-0/attempt-2/execution/stderr
STDERR_CONTENTS=
Traceback (most recent call last):
  File "/software/chip-seq-pipeline/src/encode_task_merge_fastq.py", line 105, in <module>
    main()
  File "/software/chip-seq-pipeline/src/encode_task_merge_fastq.py", line 93, in main
    merged_R1 = merge_fastqs(fastqs_R1, 'R1', args.out_dir)
  File "/software/chip-seq-pipeline/src/encode_task_merge_fastq.py", line 72, in merge_fastqs
    run_shell_cmd(cmd)
  File "/software/chip-seq-pipeline/src/encode_lib_common.py", line 319, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=26087, PGID=26087, RC=1
STDERR=gzip: /path/to/data/ChIP-Seq/H3K4me1/sample3/tmp/chip/4b3f9fc8-4dbe-42d7-9332-a02f38e26084/call-align_R1/shard-0/attempt-2/inputs/-889636323/mate1s.1.fastq.gz: No such file or directory
STDOUT=


```

**Comment by leepc12** [comment]
Check if those files actually exist there. Also check if your system allows hard-linking (`ln`). If not, use `--soft-glob-output`.

**Comment by rivison** [comment]
I've already added `glob-link-command = "ln -sL GLOB_PATTERN GLOB_DIRECTORY 2> /dev/null"` to my cromwell `backend.conf` based on your answer [here](https://github.com/ENCODE-DCC/atac-seq-pipeline/issues/213#issuecomment-590962437). Does `--soft-glob-output` do something different?

The files are there (they are links, and not broken):
```
$ ls /path/to/data/ChIP-Seq/H3K4me1/sample3/tmp/chip/4b3f9fc8-4dbe-42d7-9332-a02f38e26084/call-align/shard-0/inputs/-889636323
mate1s.1.fastq.gz  mate2s.1.fastq.gz
```

**Comment by rivison** [comment]
FYI, I tried adding `--soft-glob-output` and got the same result (errors) for sample3 and the other paired samples.

**Comment by leepc12** [comment]
`--soft-glob-output` does the same thing.
Can you try with Conda?

**Comment by rivison** [comment]
Hi Jin,

I wasn’t able to try installing the Conda version, but I found a solution to my problem that I think reveals a bug somewhere.

It appears that even with `--soft-glob-output`, the align task will make hard-links to the FASTQs when possible. When it’s able to make hard-links, the workflow runs successfully. When it’s unable to make the hard-links, it successfully makes the soft-links, but the workflow fails when it tries to use them. I was able to produce a failed workflow for sample2 above by having the owner of the FASTQ file change its permissions to `-rw-r--r--`.

My system allows hard-links in general, but we can’t hard-link files we don’t own unless they’re writable. It was just a coincidence that the flowcell containing the paired end samples was the only one I’m using that the owner hadn’t changed the permissions on the FASTQs to `-rw-rw-r--`. I've amended the issue title to reflect my findings.

Let me know if you need more info to find the source of the problem.

Thanks,
Rachael

**Comment by leepc12** [comment]
This should be fixed in latest Caper. Caper/Cromwell tries to soft-link files first if that fails then it switches to hard-linking.
