### ISSUE TITLE
Error: pipeline dependencies not found.

### ISSUE THREAD

**Issue by Barbarak17** [ENCODE-DCC/chip-seq-pipeline2#172]
**Describe the bug**

This is when running the test json provided by the pipeline.
See result below:
```
 _**Error: pipeline dependencies not found.**
Conda users: Did you activate Conda environment (conda activate encode-chip-seq-pipeline)?
    Or did you install Conda and environment correctly (bash scripts/install_conda_env.sh)?
GCP/AWS/Docker users: Did you add --docker flag to Caper command line arg?
2020-07-09 16:16:07,120 cromwell-system-akka.dispatchers.engine-dispatcher-49 INFO  - WorkflowManagerActor WorkflowActor-d90ea650-f3f7-4b98-b041-f9534f23ea98 is in a terminal state: WorkflowFailedState
2020-07-09 16:16:16,422 cromwell-system-akka.dispatchers.engine-dispatcher-77 INFO  - SingleWorkflowRunnerActor workflow finished with status 'Failed'.
2020-07-09 16:16:17,604 cromwell-system-akka.dispatchers.engine-dispatcher-81 INFO  - SingleWorkflowRunnerActor writing metadata to /Users/christopherott/.caper_tmp/chip/20200709_161439_474499/metadata.json
2020-07-09 16:16:17,626  INFO  - Workflow polling stopped
2020-07-09 16:16:17,635  INFO  - 0 workflows released by cromid-7d896fb
2020-07-09 16:16:17,638  INFO  - Shutting down WorkflowStoreActor - Timeout = 5 seconds
2020-07-09 16:16:17,640  INFO  - Shutting down WorkflowLogCopyRouter - Timeout = 5 seconds
2020-07-09 16:16:17,642  INFO  - Shutting down JobExecutionTokenDispenser - Timeout = 5 seconds
2020-07-09 16:16:17,642  INFO  - JobExecutionTokenDispenser stopped
2020-07-09 16:16:17,642 cromwell-system-akka.dispatchers.engine-dispatcher-81 INFO  - Aborting all running workflows.
2020-07-09 16:16:17,643  INFO  - WorkflowStoreActor stopped
2020-07-09 16:16:17,645  INFO  - WorkflowLogCopyRouter stopped
2020-07-09 16:16:17,645  INFO  - Shutting down WorkflowManagerActor - Timeout = 3600 seconds
2020-07-09 16:16:17,646 cromwell-system-akka.dispatchers.engine-dispatcher-81 INFO  - WorkflowManagerActor All workflows finished
2020-07-09 16:16:17,646  INFO  - WorkflowManagerActor stopped
2020-07-09 16:16:17,899  INFO  - Connection pools shut down
2020-07-09 16:16:17,900  INFO  - Shutting down SubWorkflowStoreActor - Timeout = 1800 seconds
2020-07-09 16:16:17,900  INFO  - Shutting down JobStoreActor - Timeout = 1800 seconds
2020-07-09 16:16:17,900  INFO  - Shutting down CallCacheWriteActor - Timeout = 1800 seconds
2020-07-09 16:16:17,900  INFO  - Shutting down ServiceRegistryActor - Timeout = 1800 seconds
2020-07-09 16:16:17,901  INFO  - Shutting down DockerHashActor - Timeout = 1800 seconds
2020-07-09 16:16:17,901  INFO  - Shutting down IoProxy - Timeout = 1800 seconds
2020-07-09 16:16:17,901  INFO  - SubWorkflowStoreActor stopped
2020-07-09 16:16:17,901  INFO  - CallCacheWriteActor Shutting down: 0 queued messages to process
2020-07-09 16:16:17,901  INFO  - JobStoreActor stopped
2020-07-09 16:16:17,901  INFO  - WriteMetadataActor Shutting down: 0 queued messages to process
2020-07-09 16:16:17,901  INFO  - CallCacheWriteActor stopped
2020-07-09 16:16:17,901  INFO  - KvWriteActor Shutting down: 0 queued messages to process
2020-07-09 16:16:17,902  INFO  - IoProxy stopped
2020-07-09 16:16:17,903  INFO  - ServiceRegistryActor stopped
2020-07-09 16:16:17,905  INFO  - DockerHashActor stopped
2020-07-09 16:16:17,928  INFO  - Database closed
2020-07-09 16:16:17,928  INFO  - Stream materializer shut down
2020-07-09 16:16:17,931  INFO  - WDL HTTP import resolver closed
**Workflow d90ea650-f3f7-4b98-b041-f9534f23ea98 transitioned to state Failed
2020-07-09 16:16:18,052|caper.caper|INFO| run: 1, d90ea650-f3f7-4b98-b041-f9534f23ea98, None**_
```

**OS/Platform**
- OS/Platform: [e.g. Ubuntu 16.04, Google Cloud, Stanford Sherlock/SCG cluster, ...]
- Conda version: 4.8.3
- Pipeline version: 
- Caper version: 0.8.2.1

**Caper configuration file**
Paste contents of `~/.caper/default.conf`.

```
# DO NOT use /tmp here
# Caper stores all important temp files and cached big data files here
# If not defined, Caper will make .caper_tmp/ on your local output directory
# which is defined by out-dir, --out-dir or $CWD
# Use a local absolute path here
tmp-dir=

cromwell=/Users/USERNAME/.caper/cromwell_jar/cromwell-47.jar
womtool=/Users/USERNAME/.caper/womtool_jar/womtool-47.jar
default.conf (END)
```

**Input JSON file**
The test JSON file provided by the pipeline

**Error log**
Caper automatically runs a troubleshooter for failed workflows. If it doesn't then get a `WORKFLOW_ID` of your failed workflow with `caper list` or directly use a `metadata.json` file on Caper's output directory.
```
$ caper debug [WORKFLOW_ID_OR_METADATA_JSON_FILE]

$ caper debug metadata.json
```
**Response:**

```
2020-07-09 16:33:41,207|caper.cromwell_rest_api|ERROR| Help: cannot connect to server. Check if server is dead or still spinning up.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1262, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1308, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1257, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1028, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 968, in send
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x10c144450>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/workflows/v1/query?additionalQueryResultFields=labels (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10c144450>: Failed to establish a new connection: [Errno 61] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/caper/cromwell_rest_api.py", line 256, in __request_get
    headers={'accept': 'application/json'})
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/workflows/v1/query?additionalQueryResultFields=labels (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10c144450>: 
```

**Comment by leepc12** [comment]
Check if you activated pipeline's Conda environment before running `caper` stuff.
```
 _**Error: pipeline dependencies not found.**
Conda users: Did you activate Conda environment (conda activate encode-chip-seq-pipeline)?
    Or did you install Conda and environment correctly (bash scripts/install_conda_env.sh)?
```

`caper debug` only works with a running `caper server`. I will fix github issue template.

**Comment by Barbarak17** [comment]
Thank you! I successfully activated pipeline's Conda environment before running caper. What else could be?

**Comment by Barbarak17** [comment]
I was able to figure it out, so I am closing this comment. Thanks!
