### ISSUE TITLE
Workflow failure: Failed to evaluate input 'tmp_fastqs'

### ISSUE THREAD

**Issue by Barbarak17** [ENCODE-DCC/chip-seq-pipeline2#173]
**Describe the bug**
Not sure if the issue here was a runtime error. In the metadata.json says that reason is "transpose requires all collections have the same size."
Have you seen a similar error before?

**OS/Platform**
- OS/Platform: Linux: gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16)
- Conda version: 4.8.3
- Pipeline version: the latest
- Caper version: 0.8.2.1

**Caper configuration file**
Paste contents of `~/.caper/default.conf`.

**Input JSON file**
```
{
    "chip.pipeline_type" : "tf",
    "chip.genome_tsv" : "https://storage.googleapis.com/encode-pipeline-genome-data/genome_tsv/v1/hg19_caper.tsv",
    "chip.fastqs_rep1_R1" : ["/PHShome/bk724/chip-seq-pipeline2/example_input_json/data/JB0009_H3K27ac_R1.fastq.gz"
    ],
    "chip.fastqs_rep1_R2" : ["/PHShome/bk724/chip-seq-pipeline2/example_input_json/data/JB0009_H3K27ac_R2.fastq.gz"
    ],
    "chip.ctl_fastqs_rep1_R1" : ["/PHShome/bk724/chip-seq-pipeline2/example_input_json/data/JB0009_input_R1.fastq.gz"
    ],
    "chip.ctl_fastqs_rep2_R1" : ["/PHShome/bk724/chip-seq-pipeline2/example_input_json/data/JB0009_input_R2.fastq.gz"
    ],
    "chip.paired_end" : true,
    "chip.title" : "H3K27ac",
    "chip.description" : "CLLepigenome_for_dbGAP"
}
```
**Error log**
```
submission": "2020-07-13T20:12:33.594Z",
    "status": "Failed",
    "failures": [
        {
            "causedBy": [
                {
                    "causedBy": [
                        {
                            "causedBy": [],
                            "message": "Failed to evaluate input 'tmp_fastqs' (reason 1 of 1): transpose requires all collections have the same size"
                        }
                    ],
                    "message": "Call input and runtime attributes evaluation failed for align_ctl"
                },
                {
                    "causedBy": [
                        {
                            "causedBy": [],
                            "message": "Failed to evaluate input 'tmp_fastqs' (reason 1 of 1): transpose requires all collections have the same size"
                        }
                    ],
                    "message": "Call input and runtime attributes evaluation failed for align_ctl"
                }
            ],
            "message": "Workflow failed"
        }
    ],
    "end": "2020-07-14T02:04:24.456Z",
    "start": "2020-07-13T20:12:33.727Z"
}
```
$ caper debug [WORKFLOW_ID_OR_METADATA_JSON_FILE]
```
020-07-14 09:09:15,933|caper.cromwell_rest_api|ERROR| Help: cannot connect to server. Check if server is dead or still spinning up.
Traceback (most recent call last):
  File "/PHShome/bk724/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/PHShome/bk724/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/PHShome/bk724/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/PHShome/bk724/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/PHShome/bk724/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/PHShome/bk724/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/PHShome/bk724/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/PHShome/bk724/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/PHShome/bk724/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/PHShome/bk724/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/PHShome/bk724/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/PHShome/bk724/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fa4ed18c7b8>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/PHShome/bk724/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/PHShome/bk724/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/PHShome/bk724/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/workflows/v1/query?additionalQueryResultFields=labels (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4ed18c7b8>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/PHShome/bk724/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/caper/cromwell_rest_api.py", line 256, in __request_get
    headers={'accept': 'application/json'})
  File "/PHShome/bk724/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/PHShome/bk724/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/PHShome/bk724/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/PHShome/bk724/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/PHShome/bk724/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/workflows/v1/query?additionalQueryResultFields=labels (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4ed18c7b8>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by leepc12** [comment]
If you mix up different sequential endedness (SE or PE) between exp reps and controls, then you need to define control's endedness. Add the following to your input JSON.
```
    "chip.ctl_paired_end" : false,
```

**Comment by Barbarak17** [comment]
Thanks, I fixed that but now I am getting a different error:
```
"submission": "2020-07-15T13:12:49.709Z",
    "status": "Failed",
    "failures": [
        {
            "causedBy": [
                {
                    "message": "Job chip.filter_ctl:0:2 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.",
                    "causedBy": []
                }
            ],
            "message": "Workflow failed"
        }
    ],
    "end": "2020-07-15T20:21:08.306Z",
    "start": "2020-07-15T13:12:49.821Z"
}
```

**Comment by leepc12** [comment]
Please run `caper debug metadata.json` (do it on your metadata JSON file).

**Comment by Barbarak17** [comment]
Thanks, this is the output:

```
2020-07-20 13:05:38,853|caper.cromwell_rest_api|ERROR| Help: cannot connect to server. Check if server is dead or still spinning up.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1262, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1308, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1257, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1028, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 968, in send
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x114497910>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/workflows/v1/query?additionalQueryResultFields=labels (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x114497910>: Failed to establish a new connection: [Errno 61] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/caper/cromwell_rest_api.py", line 256, in __request_get
    headers={'accept': 'application/json'})
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/workflows/v1/query?additionalQueryResultFields=labels (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x114497910>: Failed to establish a new connection: [Errno 61] Connection refused'))
```

**Comment by leepc12** [comment]
Did you run it on the directory where your `metadata.json` file resides?

**Comment by Barbarak17** [comment]
Yes.

**Comment by Barbarak17** [comment]
Thanks, I was able to locate an error on one file. It appears that numpy needs to reinstalled. I will try this and run the pipeline again. I am closing this issue.
```
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

```
