### ISSUE TITLE
Pipeline issues with gnu-sed & libopenblas.dylib mac users (solved)

### ISSUE THREAD

**Issue by Barbarak17** [ENCODE-DCC/chip-seq-pipeline2#177]
**Describe the bug**
Pipeline fails at chip.spr & chip.xcor, potentially related to shuf command. Using a mac terminal.
Error logs:

chip.spr
```
Traceback (most recent call last):
  File "/Users/barbarak/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_task_spr.py", line 143, in <module>
    main()
  File "/Users/barbarak/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_task_spr.py", line 130, in main
    ta_pr1, ta_pr2 = spr_se(args.ta, args.out_dir)
  File "/Users/barbarak/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_task_spr.py", line 54, in spr_se
    run_shell_cmd(cmd1)
  File "/Users/barbarak/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_lib_common.py", line 319, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=82727, PGID=82727, RC=64
STDERR=split: illegal option -- d
usage: split [-a sufflen] [-b byte_count] [-l line_count] [-p pattern]
             [file [prefix]]
/bin/bash: line 1: shuf: command not found
STDOUT=
```

chip.xcor
```
Traceback (most recent call last):
  File "/Users/barbarak/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_task_xcor.py", line 156, in <module>
    main()
  File "/Users/barbarak/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_task_xcor.py", line 138, in main
    args.mito_chr_name, args.out_dir)
  File "/Users/barbarak/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_lib_genomic.py", line 254, in subsample_ta_se
    run_shell_cmd(cmd)
  File "/Users/barbarak/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_lib_common.py", line 319, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=82749, PGID=82749, RC=127
STDERR=/bin/bash: line 1: shuf: command not found
STDOUT=
```

**Caper configuration file**
```
backend=local

# DO NOT use /tmp here
# Caper stores all important temp files and cached big data files here
# If not defined, Caper will make .caper_tmp/ on your local output directory
# which is defined by out-dir, --out-dir or $CWD
# Use a local absolute path here
tmp-dir=chiptestlocal

cromwell=/Users/barbarak/.caper/cromwell_jar/cromwell-47.jar
womtool=/Users/barbarak/.caper/womtool_jar/womtool-47.jar
```

**Input JSON file**
```
{
    "chip.pipeline_type" : "tf",
    "chip.aligner": "bowtie2",
    "chip.genome_tsv" : "https://storage.googleapis.com/encode-pipeline-genome-data/genome_tsv/v1/hg19_caper.tsv",
    "chip.fastqs_rep1_R1" : ["/Users/barbarak/Desktop/Barbara/data1/JB0009_H3K27ac_R1.fastq.gz"
    ],
    "chip.fastqs_rep1_R2": [],
    "chip.ctl_fastqs_rep1_R1" : ["/Users/barbarak/Desktop/Barbara//data1/JB0009_input_R1.fastq.gz"
    ],
    "chip.ctl_fastqs_rep1_R2": [],
    "chip.paired_end" : false,
    "chip.ctl_paired_end": false,
    "chip.title" : "H3K27ac",
    "chip.description" : "CLLepigenome_for_dbGAP by the Ott lab"
}

**Error log**
Caper automatically runs a troubleshooter for failed workflows. If it doesn't then get a `WORKFLOW_ID` of your failed workflow with `caper list` or directly use a `metadata.json` file on Caper's output directory.
```
$ caper debug [WORKFLOW_ID_OR_METADATA_JSON_FILE]
```
  "submission": "2020-07-22T14:51:29.232Z",
    "status": "Failed",
    "failures": [
        {
            "message": "Workflow failed",
            "causedBy": [
                {
                    "causedBy": [],
                    "message": "Job chip.spr:0:2 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details."
                },
                {
                    "message": "Job chip.xcor:0:2 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.",
                    "causedBy": []
                }
            ]
        }
    ],
    "end": "2020-07-22T17:59:23.701Z",
    "start": "2020-07-22T14:51:29.326Z"
```

**Comment by leepc12** [comment]
What is your OS? Does it have `shuf`.
Please do this for debugging.

```bash
$ shuf --version
$ split --version
```

**Comment by Barbarak17** [comment]
Thanks Jin, 

apparently I had to install coreutils and update the path because suff is linked as gshuf. I have MacOS Catalina, by the way. 
This helped to fix that error, but now call-xcor throws a different error.
```
Traceback (most recent call last):
  File "/Users/christopherott/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_task_xcor.py", line 156, in <module>
    main()
  File "/Users/christopherott/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_task_xcor.py", line 144, in main
    args.chip_seq_type, args.exclusion_range_min, args.exclusion_range_max)
  File "/Users/christopherott/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_task_xcor.py", line 109, in xcor
    run_shell_cmd(cmd2)
  File "/Users/christopherott/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_lib_common.py", line 319, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=48152, PGID=48152, RC=1
STDERR=sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
STDOUT=
```
I will install sed and see if the bug will go away.

My question is however, if call-jsd is dependent to call-xcor, because in the call-jsd error log, I see the following message:
```
ncode_task_jsd.py", line 93, in fingerprint
    run_shell_cmd(cmd)
  File "/Users/christopherott/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_lib_common.py", line 319, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=48235, PGID=48235, RC=1
STDERR=Traceback (most recent call last):
  File "/Users/christopherott/miniconda3/envs/encode-chip-seq-pipeline/bin/plotFingerprint", line 5, in <module>
    from deeptools.plotFingerprint import main
  File "/Users/christopherott/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.7/site-packages/deeptools/plotFingerprint.py", line 12, in <module>
    from scipy import interpolate
  File "/Users/christopherott/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.7/site-packages/scipy/interpolate/__init__.py", line 165, in <module>
    from .interpolate import *
  File "/Users/christopherott/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.7/site-packages/scipy/interpolate/interpolate.py", line 13, in <module>
    import scipy.special as spec
  File "/Users/christopherott/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.7/site-packages/scipy/special/__init__.py", line 633, in <module>
    from . import _ufuncs
ImportError: dlopen(/Users/christopherott/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.7/site-packages/scipy/special/_ufuncs.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libopenblas.dylib
  Referenced from: /Users/christopherott/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.7/site-packages/scipy/special/_ufuncs.cpython-37m-darwin.so
  Reason: image not found
STDOUT=
```

**Comment by leepc12** [comment]
`jsd` is not dependent on `xcor`.

It seems something is wrong with openblas on your machine?
```
Library not loaded: @rpath/libopenblas.dylib
  Referenced from: /Users/barbarak/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.7/site-packages/scipy/special/_ufuncs.cpython-37m-darwin.so
```

If conda doesn't work well, can you install docker on your machine and try with `caper run ... --docker`?

**Comment by Barbarak17** [comment]
Thanks, I will try updating openblas and if this won't work I will try docker.
By the way, the call-xcor bug was fixed by installing sed.

**Comment by Barbarak17** [comment]
I was able to fix the libopenblas.dylib with a symlink (it appeared as libopenblas.0.dylib in my environment.)
Now I have a different bug, which afferts both xcor and spr. I am posting here the error files. Please let me know if you have any idea how to fix this.
call.spr stderr
```
Traceback (most recent call last):
  File "/Users/christopherott/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_task_spr.py", line 143, in <module>
    main()
  File "/Users/christopherott/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_task_spr.py", line 130, in main
    ta_pr1, ta_pr2 = spr_se(args.ta, args.out_dir)
  File "/Users/christopherott/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_task_spr.py", line 54, in spr_se
    run_shell_cmd(cmd1)
  File "/Users/christopherott/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_lib_common.py", line 319, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=88695, PGID=88695, RC=64
STDERR=split: illegal option -- d
usage: split [-a sufflen] [-b byte_count] [-l line_count] [-p pattern]
             [file [prefix]]
shuf: ‘/dev/fd/63’: end of file
STDOUT=
```
call.xcor stderr
```
Traceback (most recent call last):
  File "/Users/christopherott/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_task_xcor.py", line 156, in <module>
    main()
  File "/Users/christopherott/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_task_xcor.py", line 138, in main
    args.mito_chr_name, args.out_dir)
  File "/Users/christopherott/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_lib_genomic.py", line 254, in subsample_ta_se
    run_shell_cmd(cmd)
  File "/Users/christopherott/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_lib_common.py", line 319, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=88686, PGID=88686, RC=1
STDERR=shuf: ‘/dev/fd/63’: end of file
STDOUT=
```

**Comment by leepc12** [comment]
You may need to install GNU `split` too. Please try with docker.

**Comment by Barbarak17** [comment]
Are there docker instructions somewhere? I am not very familiar with docker, but I will definitely try.

**Comment by leepc12** [comment]
Do not activate pipeline's Conda environment.
```
$ pip install caper
```
Install docker somehow on your computer. Just add `--docker` flag to the run command line. Then Caper will find corresponding docker image for the pipeline (`encodedcc/chip-seq-pipeline:VERSION`).
```
$ caper run ... --docker
```

**Comment by Barbarak17** [comment]
I tried with docker twice and it just stalls at call.align for hours. With conda this step lasts less than 2hours. Not sure what the issue is with docker.

**Comment by Barbarak17** [comment]
I was finally able to run the pipeline successfully. The information below is for mac terminal users with conda environment that may run into the same issues.

- Cleaned conda tarballs 
- Uninstalled pipeline's environment and installed again.
- Added coreutils and gbu-sed to the path
`PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"

PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"`

- Symlinked libopenblas.dylib in the lib folder at the pipeline's environment. This is because by default it appears as libopenblas.0.dylib, therefore the pipeline cannot find and load the library.
`ln -s  libopenblasp-r0.2.20.dylib libopenblas.dylib`

**Comment by leepc12** [comment]
Thanks, this is super helpful.
Added `coreutils` (including GNU `split` and `shuf`) and `sed` to the Conda env installer.
