### ISSUE TITLE
Pipeline stalled at filter step for one replicate

### ISSUE THREAD

**Issue by sckinta** [ENCODE-DCC/chip-seq-pipeline2#180]
**Describe the bug**
I have three replicates (with three input) to run chip-seq pipeline2. Only 2 replicates finished filter step and one replicate was stalled at filtered mark dups step (on nodup.bam were generated). One of two that finished filter step went forward for xcor. (please see [log file](https://www.dropbox.com/s/2lu325xgzrkf14g/workflow.72b37ba0-ce7a-45f0-9642-826bcec80519.log?dl=0)).

I tried the pipeline with the same config a few days ago. The pipeline stalled at the same step for days (before I killed it).  The `caper debug` report "Found a heartbeat file but it has been expired" which I don't know which step is time-out. 

Also, I am wondering whether there is a way to resume the pipeline by feeding workflow id? Re-running the pipeline from the scratch with error like this is very time-consuming.

**OS/Platform**
- OS/Platform: CentOS Linux 7 (Core) [SGE]
- Conda version: conda 4.6.14.
- Pipeline version: [v1.4.0.1]
- Caper version: 1.1.0

**Caper configuration file**
backend=sge
sge-pe=smp

# DO NOT use /tmp here
# Caper stores all important temp files and cached big data files here
# If not defined, Caper will make .caper_tmp/ on your local output directory
# which is defined by out-dir, --out-dir or $CWD
# Use a local absolute path here
tmp-dir=/mnt/isilon/sfgi/suc1/tmp

cromwell=/home/suc1/.caper/cromwell_jar/cromwell-47.jar
womtool=/home/suc1/.caper/womtool_jar/womtool-47.jar

**Input JSON file**
{
"chip.title" : "Treg",
"chip.description" : "This is an input JSON for paired-end sample.",
"chip.pipeline_type" : "tf",
"chip.aligner" : "bowtie2",
"chip.align_only" : false,
"chip.true_rep_only" : true,
"chip.genome_tsv" : "/mnt/isilon/sfgi/programs/chip-seq-pipeline2/genome_db/mm9.v2/mm9.tsv",
"chip.paired_end" : true,

"chip.fastqs_rep1_R1" : [ "/mnt/isilon/sfgi/suc1/analyses/wells/chipSeq/Treg_Ikaros/encode/Treg/IK_WT_Treg_CHIP_1_R1.fastq.gz"],
"chip.fastqs_rep1_R2" : [ "/mnt/isilon/sfgi/suc1/analyses/wells/chipSeq/Treg_Ikaros/encode/Treg/IK_WT_Treg_CHIP_1_R2.fastq.gz"],
"chip.fastqs_rep2_R1" : [ "/mnt/isilon/sfgi/suc1/analyses/wells/chipSeq/Treg_Ikaros/encode/Treg/IK_WT_Treg_CHIP_2_R1.fastq.gz"],
"chip.fastqs_rep2_R2" : [ "/mnt/isilon/sfgi/suc1/analyses/wells/chipSeq/Treg_Ikaros/encode/Treg/IK_WT_Treg_CHIP_2_R2.fastq.gz"],
"chip.fastqs_rep3_R1" : [ "/mnt/isilon/sfgi/suc1/analyses/wells/chipSeq/Treg_Ikaros/encode/Treg/IK_WT_Treg_CHIP_3_R1.fastq.gz"],
"chip.fastqs_rep3_R2" : [ "/mnt/isilon/sfgi/suc1/analyses/wells/chipSeq/Treg_Ikaros/encode/Treg/IK_WT_Treg_CHIP_3_R2.fastq.gz"],
"chip.ctl_paired_end" : true,
"chip.ctl_fastqs_rep1_R1" : [ "/mnt/isilon/sfgi/suc1/analyses/wells/chipSeq/Treg_Ikaros/encode/Treg/WT_Treg_input_1_R1.fastq.gz"],
"chip.ctl_fastqs_rep1_R2" : [ "/mnt/isilon/sfgi/suc1/analyses/wells/chipSeq/Treg_Ikaros/encode/Treg/WT_Treg_input_1_R2.fastq.gz"],
"chip.ctl_fastqs_rep2_R1" : [ "/mnt/isilon/sfgi/suc1/analyses/wells/chipSeq/Treg_Ikaros/encode/Treg/WT_Treg_input_2_R1.fastq.gz"],
"chip.ctl_fastqs_rep2_R2" : [ "/mnt/isilon/sfgi/suc1/analyses/wells/chipSeq/Treg_Ikaros/encode/Treg/WT_Treg_input_2_R2.fastq.gz"],
"chip.ctl_fastqs_rep3_R1" : [ "/mnt/isilon/sfgi/suc1/analyses/wells/chipSeq/Treg_Ikaros/encode/Treg/WT_Treg_input_3_R1.fastq.gz"],
"chip.ctl_fastqs_rep3_R2" : [ "/mnt/isilon/sfgi/suc1/analyses/wells/chipSeq/Treg_Ikaros/encode/Treg/WT_Treg_input_3_R2.fastq.gz"],
"chip.crop_length" : 0,

"chip.mapq_thresh" : 30,
"chip.dup_marker" : "picard",
"chip.no_dup_removal" : false,

"chip.subsample_reads" : 0,
"chip.ctl_subsample_reads" : 0,
"chip.xcor_subsample_reads" : 15000000,

"chip.xcor_trim_bp" : 50,
"chip.use_filt_pe_ta_for_xcor" : false,

"chip.always_use_pooled_ctl" : false,
"chip.ctl_depth_ratio" : 1.2,

"chip.peak_caller" : null,
"chip.cap_num_peak_macs2" : 500000,
"chip.pval_thresh" : 0.01,
"chip.fdr_thresh" : 0.01,
"chip.idr_thresh" : 0.05,
"chip.cap_num_peak_spp" : 300000,

"chip.enable_jsd" : true,
"chip.enable_gc_bias" : true,
"chip.enable_count_signal_track" : false,

"chip.filter_chrs" : [],

"chip.align_cpu" : 4,
"chip.align_mem_mb" : 20000,
"chip.align_time_hr" : 48,

"chip.filter_cpu" : 2,
"chip.filter_mem_mb" : 20000,
"chip.filter_time_hr" : 24,

"chip.bam2ta_cpu" : 2,
"chip.bam2ta_mem_mb" : 10000,
"chip.bam2ta_time_hr" : 6,

"chip.spr_mem_mb" : 16000,

"chip.jsd_cpu" : 2,
"chip.jsd_mem_mb" : 12000,
"chip.jsd_time_hr" : 6,

"chip.xcor_cpu" : 2,
"chip.xcor_mem_mb" : 16000,
"chip.xcor_time_hr" : 24,

"chip.call_peak_cpu" : 2,
"chip.call_peak_mem_mb" : 16000,
"chip.call_peak_time_hr" : 72,

"chip.macs2_signal_track_mem_mb" : 16000,
"chip.macs2_signal_track_time_hr" : 24,

"chip.gc_bias_picard_java_heap" : "10G"
}

**Error log**
Caper automatically runs a troubleshooter for failed workflows. If it doesn't then get a `WORKFLOW_ID` of your failed workflow with `caper list` or directly use a `metadata.json` file on Caper's output directory.
```
$ caper debug 72b37ba0

2020-08-11 11:01:38,897|caper.server_heartbeat|ERROR| Found a heartbeat file but it has been expired (> timeout). ~/.caper/default_server_heartbeat
Traceback (most recent call last):
  File "/mnt/isilon/sfgi/programs/miniconda3/envs/encode-chip-seq-pipeline/bin/caper", line 13, in <module>
    main()
  File "/mnt/isilon/sfgi/programs/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/caper/cli.py", line 504, in main
    client(parsed_args)
  File "/mnt/isilon/sfgi/programs/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/caper/cli.py", line 269, in client
    subcmd_troubleshoot(c, args)
  File "/mnt/isilon/sfgi/programs/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/caper/cli.py", line 454, in subcmd_troubleshoot
    wf_ids_or_labels=args.wf_id_or_label, embed_subworkflow=True
  File "/mnt/isilon/sfgi/programs/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/caper/caper_client.py", line 129, in metadata
    embed_subworkflow=embed_subworkflow,
  File "/mnt/isilon/sfgi/programs/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/caper/cromwell_rest_api.py", line 144, in get_metadata
    workflows = self.find(workflow_ids, labels)
  File "/mnt/isilon/sfgi/programs/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/caper/cromwell_rest_api.py", line 226, in find
    CromwellRestAPI.ENDPOINT_WORKFLOWS, params=CromwellRestAPI.PARAMS_WORKFLOWS
  File "/mnt/isilon/sfgi/programs/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/caper/cromwell_rest_api.py", line 299, in __request_get
    ) from None
Exception: Failed to connect to Cromwell server. req=GET, url=http://localhost:8000/api/workflows/v1/query
```

**Comment by leepc12** [comment]
`caper debug WORKFLOW_ID` is for a running Caper server only.
Try with your `metadata.json` (output of Caper/Cromwell) to debug.
```bash
$ caper debug YOUR_METADATA_JSON_FILE_PATH
```

**Comment by leepc12** [comment]
Closing this due to inactivity.
