### ISSUE TITLE
croo

### ISSUE THREAD

**Issue by summer-lemon** [ENCODE-DCC/chip-seq-pipeline2#189]
There was no error in the previous operation. The error reported in today's operation is as follows. I think it is a croo problem, but I don't know how to solve it.
Traceback (most recent call last):
  File "/software/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/software/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/software/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/software/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/software/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/software/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/software/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/urllib3/connection.py", line 300, in connect
    conn = self._new_conn()
  File "/software/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x2b716b0ce828>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/software/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/software/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/software/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /encode-pipeline-output-definition/chip.croo.json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x2b716b0ce828>: Failed to establish a new connection: [Errno 110] Connection timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/software/miniconda3/envs/encode-chip-seq-pipeline/bin/croo", line 14, in <module>
    main()
  File "/software/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/croo/cli.py", line 218, in main
    no_checksum=args['no_checksum'])
  File "/software/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/croo/croo.py", line 85, in __init__
    f = AutoURI(out_def_json).localize_on(self._tmp_dir)
  File "/software/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/autouri/autouri.py", line 341, in localize_on
    loc_prefix=loc_prefix, return_flag=return_flag, depth=depth)
  File "/software/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/autouri/autouri.py", line 541, in localize
    src_uri.cp(dest_uri=loc_uri, make_md5_file=make_md5_file)
  File "/software/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/autouri/autouri.py", line 298, in cp
    if not self._cp(dest_uri=d):
  File "/software/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/autouri/httpurl.py", line 133, in _cp
    headers=requests.utils.default_headers())
  File "/software/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/software/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/software/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/software/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/software/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /encode-pipeline-output-definition/chip.croo.json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x2b716b0ce828>: Failed to establish a new connection: [Errno 110] Connection timed out',))

**Comment by leepc12** [comment]
Sorry about very late response.
I think this should already been fixed in the latest Caper/croo.
