### ISSUE TITLE
lib/python3.6/configparser.py", line 846, in items  d.update(self._sections[section]) KeyError: 'defaults'

### ISSUE THREAD

**Issue by bony45** [ENCODE-DCC/chip-seq-pipeline2#198]
I was trying to run IDR pipeline . I could run this pipeline one time successfully my second run is coming up with following error. 
i am  running this pipeline as 
caper run /lower_bay/home/bony.dekumar/chip-seq-pipeline2/chip.wdl -i mediator_6_json 
## **Describe the bug**
Traceback (most recent call last):
  File "/lower_bay/home/bony.dekumar/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/configparser.py", line 846, in items
    d.update(self._sections[section])
KeyError: 'defaults'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lower_bay/home/bony.dekumar/miniconda3/envs/encode-chip-seq-pipeline/bin/caper", line 13, in <module>
    main()
  File "/lower_bay/home/bony.dekumar/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/caper/cli.py", line 481, in main
    parser, _ = get_parser_and_defaults()
  File "/lower_bay/home/bony.dekumar/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/caper/caper_args.py", line 699, in get_parser_and_defaults
    conf_key_map=CAPER_1_0_0_PARAM_KEY_NAME_CHANGE,
  File "/lower_bay/home/bony.dekumar/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/caper/arg_tool.py", line 120, in update_parsers_defaults_with_conf
    no_strip_quote=no_strip_quote,
  File "/lower_bay/home/bony.dekumar/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/site-packages/caper/arg_tool.py", line 47, in read_from_conf
    d_ = dict(config.items(conf_section))
  File "/lower_bay/home/bony.dekumar/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.6/configparser.py", line 849, in items
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'defaults'

## **OS/Platform**
- OS/Platform: [e.g. Ubuntu 18.04, Google Cloud, Stanford Sherlock/SCG cluster, ...]
- Conda version: If you used Conda (`$ conda --version`).
- Pipeline version: [e.g. v1.6.0]
- Caper version: [e.g. v1.2.0]

## **Caper configuration file**
Paste contents of `~/.caper/default.conf`.
```ini
PASTE CAPER CONF CONTENTS HERE
```

## **Input JSON file**
Paste contents of your input JSON file.
```json
{
    "chip.title" : "Example (paired-end)",
    "chip.description" : "This is an template input JSON for paired-end sample.",

    "chip.pipeline_type" : "tf",
    "chip.aligner" : "bowtie2",
    "chip.align_only" : false,
    "chip.true_rep_only" : false,

    "chip.genome_tsv" : "/lower_bay/home/bony.dekumar/chip-seq-pipeline2/mm10.tsv",

    "chip.paired_end" : false,
    "chip.ctl_paired_end" : false,

    "chip.always_use_pooled_ctl" : true,

    "chip.fastqs_rep1_R1" : [ "s_1_1_CATTTT.fastq.gz", "s_2_1_CATTTT.fastq.gz" ],
    "chip.fastqs_rep2_R1" : [ "s_1_1_CCAACA.fastq.gz", "s_2_1_CCAACA.fastq.gz" ],

    "chip.ctl_fastqs_rep1_R1" : [ "s_1_1_CTATAC.fastq.gz","s_2_1_CTATAC.fastq.gz" ],
    "chip.ctl_fastqs_rep2_R1" : [ "s_1_1_CTCAGA.fastq.gz","s_2_1_CTCAGA.fastq.gz" ]
}

```

## **Troubleshooting result**

If you ran `caper run` without Caper server then Caper automatically runs a troubleshooter for failed workflows. Find troubleshooting result in the bottom of Caper's screen log.

If you ran `caper submit` with a running Caper server then first find your workflow ID (1st column) with `caper list` and run `caper debug [WORKFLOW_ID]`.

Paste troubleshooting result.
```
PASTE TROUBLESHOOTING RESULT HERE
```

**Comment by leepc12** [comment]
Try to uninstall caper and re-install the latest caper (v1.4.1). And then to make sure run the following:
```bash
$ pip install autouri --upgrade
$ pip install caper --upgrade
```

**Comment by leepc12** [comment]
Closing this due to inactivity.
already fixed all pip/conda issues.
