### ISSUE TITLE
libreadline.so.6: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by tyewaichung** [ENCODE-DCC/chip-seq-pipeline2#254]
Hello,
This time there is a new problem
Check the content of stderr for potential additional information: /home/zhong/chip-seq-pipeline2-2.1.2/chip/f39b9431-ba54-4d6e-9894-9e5f32a42e3b/call-xcor/shard-0/attempt-2/execution/stderr.
 [First 3000 bytes]:Traceback (most recent call last):
  File "/home/zhong/miniconda3/envs/encode-chip-seq-pipeline-spp/bin/encode_task_xcor.py", line 156, in <module>
    main()
  File "/home/zhong/miniconda3/envs/encode-chip-seq-pipeline-spp/bin/encode_task_xcor.py", line 144, in main
    args.chip_seq_type, args.exclusion_range_min, args.exclusion_range_max)
  File "/home/zhong/miniconda3/envs/encode-chip-seq-pipeline-spp/bin/encode_task_xcor.py", line 105, in xcor
    run_shell_cmd(cmd1)
  File "/home/zhong/miniconda3/envs/encode-chip-seq-pipeline-spp/bin/encode_lib_common.py", line 359, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=18196, PGID=18196, RC=127, DURATION_SEC=0.0
STDERR=/home/zhong/miniconda3/envs/encode-chip-seq-pipeline-spp/lib/R/bin/exec/R: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory
STDOUT=
[](url)
my system is ubuntu 18.0 
[cromwell.out.1.txt](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/7692622/cromwell.out.1.txt)

**Comment by tyewaichung** [comment]
done
