### ISSUE TITLE
”caper init local“ error

### ISSUE THREAD

**Issue by songxh1996** [ENCODE-DCC/chip-seq-pipeline2#293]
**When I run caper init local, I get the following error, how can I solve it?**
```

2023-04-05 22:02:14,771|caper.cromwell|INFO| Installing Cromwell JAR... https://github.com/broadinstitute/cromwell/releases/download/82/cromwell-82.jar
2023-04-05 22:02:14,771|autouri.autouri|INFO| cp: (b8f59ec7) started. src=https://github.com/broadinstitute/cromwell/releases/download/82/cromwell-82.jar, dest=/home/songxh/.caper/cromwell_jar/cromwell-82.jar
Traceback (most recent call last):
  File "/home/songxh/miniconda3/envs/chipseq_caper/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/songxh/miniconda3/envs/chipseq_caper/lib/python3.11/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/songxh/miniconda3/envs/chipseq_caper/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/songxh/miniconda3/envs/chipseq_caper/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/songxh/miniconda3/envs/chipseq_caper/lib/python3.11/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/songxh/miniconda3/envs/chipseq_caper/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/songxh/miniconda3/envs/chipseq_caper/lib/python3.11/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/home/songxh/miniconda3/envs/chipseq_caper/lib/python3.11/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f94be7aafd0>, 'Connection to github.com timed out. (connect timeout=None)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/songxh/miniconda3/envs/chipseq_caper/lib/python3.11/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/songxh/miniconda3/envs/chipseq_caper/lib/python3.11/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/songxh/miniconda3/envs/chipseq_caper/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /broadinstitute/cromwell/releases/download/82/cromwell-82.jar (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f94be7aafd0>, 'Connection to github.com timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/songxh/miniconda3/envs/chipseq_caper/bin/caper", line 13, in <module>
    main()
  File "/home/songxh/miniconda3/envs/chipseq_caper/lib/python3.11/site-packages/caper/cli.py", line 709, in main
    init_caper_conf(parsed_args.conf, parsed_args.platform)
  File "/home/songxh/miniconda3/envs/chipseq_caper/lib/python3.11/site-packages/caper/caper_init.py", line 181, in init_caper_conf
    '{key}={val}\n'.format(key='cromwell', val=cromwell.install_cromwell())
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/songxh/miniconda3/envs/chipseq_caper/lib/python3.11/site-packages/caper/cromwell.py", line 480, in install_cromwell
    self._cromwell = install_file(
                     ^^^^^^^^^^^^^
  File "/home/songxh/miniconda3/envs/chipseq_caper/lib/python3.11/site-packages/caper/cromwell.py", line 33, in install_file
    return AutoURI(f).cp(path)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/songxh/miniconda3/envs/chipseq_caper/lib/python3.11/site-packages/autouri/autouri.py", line 338, in cp
    if not self._cp(dest_uri=d):
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/songxh/miniconda3/envs/chipseq_caper/lib/python3.11/site-packages/autouri/httpurl.py", line 142, in _cp
    r = requests.get(
        ^^^^^^^^^^^^^
  File "/home/songxh/miniconda3/envs/chipseq_caper/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/songxh/miniconda3/envs/chipseq_caper/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/songxh/miniconda3/envs/chipseq_caper/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/songxh/miniconda3/envs/chipseq_caper/lib/python3.11/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/songxh/miniconda3/envs/chipseq_caper/lib/python3.11/site-packages/requests/adapters.py", line 553, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /broadinstitute/cromwell/releases/download/82/cromwell-82.jar (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f94be7aafd0>, 'Connection to github.com timed out. (connect timeout=None)'))
```

**Comment by leepc12** [comment]
Does your computer have internet connection?

**Comment by songxh1996** [comment]
Computer has internet connection

**Comment by leepc12** [comment]
Please run `wget https://github.com/broadinstitute/cromwell/releases/download/82/cromwell-82.jar` to check if you can download Cromwell.
