### ISSUE TITLE
Failure to find peak file

### ISSUE THREAD

**Issue by kdemuren** [ENCODE-DCC/chip-seq-pipeline2#54]
Now, running the pipeline on my actual data, one run stopped when it came to the IDR steps, with this specific error:
```
[2019-02-07 03:01:30,91] [[38;5;1merror[0m] WorkflowManagerActor Workflow 73108c41-3432-4ab2-9f3d-92b89dd0b538 failed (during ExecutingWorkflowState): Job chip.idr:0:1 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.
Check the content of stderr for potential additional information: /net/bmc-pub9/data/boyerlab/users/kdemuren/chip-seq-pipeline2/cromwell-executions/chip/73108c41-3432-4ab2-9f3d-92b89dd0b538/call-idr/shard-0/execution/stderr.
 Traceback (most recent call last):
  File "/home/kdemuren/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_idr.py", line 169, in <module>
    main()
  File "/home/kdemuren/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_idr.py", line 144, in main
    assert_file_not_empty(bfilt_idr_peak)
  File "/net/bmc-pub9/data/boyerlab/users/kdemuren/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_common.py", line 176, in assert_file_not_empty
    raise Exception('File is empty ({}). Help: {}'.format(f,help))
Exception: File is empty (rep1-rep2.idr0.05.bfilt.narrowPeak.gz). Help: 
```
With the same JSON file (but different ChIP data), I've had two successful runs, again using qlogin with memory/time allocation.

Log attached: 
[log_CM_Rad21.txt](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/2841791/log_CM_Rad21.txt)

Error tarball: 
[debug_54.tar.gz](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/2841803/debug_54.tar.gz)

**Comment by leepc12** [comment]
It looks like that none of the peaks from true replicate pair (rep1-rep2) passed the IDR threshold. Other IDR jobs (pooled, pseudo replicated) were successful.
Can you increase `chip.idr_thresh` a bit like 0.2 (it's 0.05 by default) for testing purpose and try again?

**Comment by kdemuren** [comment]
Got the same error - is there an option to skip the IDR portion but get the rest of the QC (cross-correlation analysis, etc)?

**Comment by leepc12** [comment]
Use align_only mode in your input JSON file to disable all peak-calling, IDR steps. You will still get cross-corr stats.
```
"chip.align_only" : true,
```

Or you can edit this line in `chip.wdl` to disable IDR.
https://github.com/ENCODE-DCC/chip-seq-pipeline2/blob/master/chip.wdl#L190
```
Boolean enable_idr = false
```

**Comment by leepc12** [comment]
Closing this due to long inactivity
