### ISSUE TITLE
[error] Error parsing generated wdl:

### ISSUE THREAD

**Issue by Runuply** [ENCODE-DCC/chip-seq-pipeline2#65]
Got issues when running the test samples. 

(encode-chip-seq-pipeline) [ye.liu@submit chip-seq-pipeline2]$ java -jar -Dconfig.file=backends/backend.conf cromwell-34.jar run chip.wdl -i ${INPUT} -o workflow_opts/singularity.json -m ${PIPELINE_METADATA}
[2019-04-16 16:17:55,29] [info] Running with database db.url = jdbc:hsqldb:mem:56b66269-54d2-4a0e-af42-3e525d21846c;shutdown=false;hsqldb.tx=mvcc
[2019-04-16 16:18:04,19] [info] Running migration RenameWorkflowOptionsInMetadata with a read batch size of 100000 and a write batch size of 100000
[2019-04-16 16:18:04,20] [info] [RenameWorkflowOptionsInMetadata] 100%
[2019-04-16 16:18:04,29] [info] Running with database db.url = jdbc:hsqldb:mem:079abec0-ecbf-460b-972f-53d84fcb434c;shutdown=false;hsqldb.tx=mvcc
[2019-04-16 16:18:04,66] [warn] This actor factory is deprecated. Please use cromwell.backend.google.pipelines.v1alpha2.PipelinesApiLifecycleActorFactory for PAPI v1 or cromwell.backend.google.pipelines.v2alpha1.PipelinesApiLifecycleActorFactory for PAPI v2
[2019-04-16 16:18:04,69] [warn] Couldn't find a suitable DSN, defaulting to a Noop one.
[2019-04-16 16:18:04,69] [info] Using noop to send events.
[2019-04-16 16:18:05,00] [info] Slf4jLogger started
[2019-04-16 16:18:05,25] [info] Workflow heartbeat configuration:
{
  "cromwellId" : "cromid-4749fc3",
  "heartbeatInterval" : "2 minutes",
  "ttl" : "10 minutes",
  "writeBatchSize" : 10000,
  "writeThreshold" : 10000
}
[2019-04-16 16:18:05,29] [info] Metadata summary refreshing every 2 seconds.
[2019-04-16 16:18:05,36] [info] CallCacheWriteActor configured to flush with batch size 100 and process rate 3 seconds.
[2019-04-16 16:18:05,36] [info] WriteMetadataActor configured to flush with batch size 200 and process rate 5 seconds.
[2019-04-16 16:18:05,36] [info] KvWriteActor configured to flush with batch size 200 and process rate 5 seconds.
[2019-04-16 16:18:06,17] [info] JobExecutionTokenDispenser - Distribution rate: 50 per 1 seconds.
[2019-04-16 16:18:06,19] [info] SingleWorkflowRunnerActor: Version 34
[2019-04-16 16:18:06,19] [info] JES batch polling interval is 33333 milliseconds
[2019-04-16 16:18:06,19] [info] JES batch polling interval is 33333 milliseconds
[2019-04-16 16:18:06,19] [info] JES batch polling interval is 33333 milliseconds
[2019-04-16 16:18:06,19] [info] PAPIQueryManager Running with 3 workers
[2019-04-16 16:18:06,20] [info] SingleWorkflowRunnerActor: Submitting workflow
[2019-04-16 16:18:06,26] [info] Unspecified type (Unspecified version) workflow 7f0b27fc-a2c9-42c2-b9ea-2cd6517162c3 submitted
[2019-04-16 16:18:06,31] [info] SingleWorkflowRunnerActor: Workflow submitted 7f0b27fc-a2c9-42c2-b9ea-2cd6517162c3
[2019-04-16 16:18:06,32] [info] 1 new workflows fetched
[2019-04-16 16:18:06,32] [info] WorkflowManagerActor Starting workflow 7f0b27fc-a2c9-42c2-b9ea-2cd6517162c3
[2019-04-16 16:18:06,33] [warn] SingleWorkflowRunnerActor: received unexpected message: Done in state RunningSwraData
[2019-04-16 16:18:06,33] [info] WorkflowManagerActor Successfully started WorkflowActor-7f0b27fc-a2c9-42c2-b9ea-2cd6517162c3
[2019-04-16 16:18:06,33] [info] Retrieved 1 workflows from the WorkflowStoreActor
[2019-04-16 16:18:06,34] [info] WorkflowStoreHeartbeatWriteActor configured to flush with batch size 10000 and process rate 2 minutes.
[2019-04-16 16:18:06,41] [info] MaterializeWorkflowDescriptorActor [7f0b27fc]: Parsing workflow as WDL draft-2
[2019-04-16 16:19:25,60] [info] MaterializeWorkflowDescriptorActor [7f0b27fc]: Call-to-Backend assignments: chip.idr -> local, chip.bam2ta_no_filt -> local, chip.pool_ta_pr2 -> local, chip.spp_ppr2 -> local, chip.overlap -> local, chip.idr_pr -> local, chip.macs2_ppr2 -> local, chip.bam2ta_no_filt_R1 -> local, chip.overlap_ppr -> local, chip.fingerprint -> local, chip.macs2_pr2 -> local, chip.choose_ctl -> local, chip.bam2ta -> local, chip.bwa -> local, chip.merge_fastq_ctl -> local, chip.macs2 -> local, chip.idr_ppr -> local, chip.pool_ta -> local, chip.macs2_pooled -> local, chip.filter_ctl -> local, chip.read_genome_tsv -> local, chip.bwa_R1 -> local, chip.spp_pr2 -> local, chip.spp -> local, chip.spp_pooled -> local, chip.filter -> local, chip.xcor -> local, chip.macs2_ppr1 -> local, chip.bwa_ctl -> local, chip.macs2_pr1 -> local, chip.spr -> local, chip.qc_report -> local, chip.spp_pr1 -> local, chip.reproducibility_idr -> local, chip.spp_ppr1 -> local, chip.fraglen_mean -> local, chip.overlap_pr -> local, chip.bam2ta_ctl -> local, chip.reproducibility_overlap -> local, chip.trim_fastq -> local, chip.merge_fastq -> local, chip.pool_ta_ctl -> local, chip.pool_ta_pr1 -> local
[2019-04-16 16:19:25,66] [error] Error parsing generated wdl:

java.lang.RuntimeException: Error parsing generated wdl:

	at cromwell.backend.impl.sfs.config.ConfigWdlNamespace.<init>(ConfigWdlNamespace.scala:55)
	at cromwell.backend.impl.sfs.config.ConfigInitializationActor.configWdlNamespace$lzycompute(ConfigInitializationActor.scala:39)
	at cromwell.backend.impl.sfs.config.ConfigInitializationActor.configWdlNamespace(ConfigInitializationActor.scala:39)
	at cromwell.backend.impl.sfs.config.ConfigInitializationActor.declarationValidations$lzycompute(ConfigInitializationActor.scala:42)
	at cromwell.backend.impl.sfs.config.ConfigInitializationActor.declarationValidations(ConfigInitializationActor.scala:41)
	at cromwell.backend.impl.sfs.config.ConfigInitializationActor.runtimeAttributesBuilder$lzycompute(ConfigInitializationActor.scala:53)
	at cromwell.backend.impl.sfs.config.ConfigInitializationActor.runtimeAttributesBuilder(ConfigInitializationActor.scala:52)
	at cromwell.backend.standard.StandardInitializationActor.coerceDefaultRuntimeAttributes(StandardInitializationActor.scala:82)
	at cromwell.backend.BackendWorkflowInitializationActor.initSequence(BackendWorkflowInitializationActor.scala:154)
	at cromwell.backend.BackendWorkflowInitializationActor.initSequence$(BackendWorkflowInitializationActor.scala:152)
	at cromwell.backend.standard.StandardInitializationActor.initSequence(StandardInitializationActor.scala:44)
	at cromwell.backend.BackendWorkflowInitializationActor$$anonfun$receive$1.$anonfun$applyOrElse$1(BackendWorkflowInitializationActor.scala:145)
	at cromwell.backend.BackendLifecycleActor.performActionThenRespond(BackendLifecycleActor.scala:44)
	at cromwell.backend.BackendLifecycleActor.performActionThenRespond$(BackendLifecycleActor.scala:40)
	at cromwell.backend.standard.StandardInitializationActor.performActionThenRespond(StandardInitializationActor.scala:44)
	at cromwell.backend.BackendWorkflowInitializationActor$$anonfun$receive$1.applyOrElse(BackendWorkflowInitializationActor.scala:145)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at cromwell.backend.standard.StandardInitializationActor.aroundReceive(StandardInitializationActor.scala:44)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.NullPointerException: null
	at wdl.draft2.model.WdlNamespace$.apply(WdlNamespace.scala:196)
	at wdl.draft2.model.WdlNamespace$.$anonfun$load$1(WdlNamespace.scala:160)
	at scala.util.Try$.apply(Try.scala:209)
	at wdl.draft2.model.WdlNamespace$.load(WdlNamespace.scala:160)
	at wdl.draft2.model.WdlNamespace$.loadUsingSource(WdlNamespace.scala:156)
	at cromwell.backend.impl.sfs.config.ConfigWdlNamespace.<init>(ConfigWdlNamespace.scala:53)
	... 27 common frames omitted

**Comment by Runuply** [comment]
It seems to work after adding `unset PYTHONPATH` and `export PYTHONNOUSERSITE=True`. There was a similar issue in the atac pipeline.

-I am running on HPC

**Comment by leepc12** [comment]
This is a bug in the `backends/backend.conf` file and will be fixed in the next release.
