### ISSUE TITLE
resumer.py fails on metadata.json generated for histone chipseq run 

### ISSUE THREAD

**Issue by annashcherbina** [ENCODE-DCC/chip-seq-pipeline2#67]
@leepc12  The pipeline is run on sherlock. 

1. The original json input file is: 

`/oak/stanford/groups/akundaje/projects/GECCO/scacheri_46_h3k27ac_chipseq/output_hg19/589N/589N.json`

The resulting metadata file is: 
`/oak/stanford/groups/akundaje/projects/GECCO/scacheri_46_h3k27ac_chipseq/output_hg19/589N/metadata.json`

The output log file is: 
`/oak/stanford/groups/akundaje/projects/GECCO/scacheri_46_h3k27ac_chipseq/logs_hg19/589N.o`

The error log file is: 
`/oak/stanford/groups/akundaje/projects/GECCO/scacheri_46_h3k27ac_chipseq/logs_hg19/589N.e`

(basically the job was cancelled because it hit the 24 hour time limit, I want to restart and allocate more time). 

2. I am running: 

```
 python ~/chip-seq-pipeline2/utils/resumer/resumer.py /oak/stanford/groups/akundaje/projects/GECCO/scacheri_46_h3k27ac_chipseq/output_hg19/589N/metadata.json
```
The code fails with the following stack trace: 

Traceback (most recent call last):
  File "/home/users/annashch/chip-seq-pipeline2/utils/resumer/resumer.py", line 100, in <module>
    main()
  File "/home/users/annashch/chip-seq-pipeline2/utils/resumer/resumer.py", line 86, in main
    workflow_id, org_input_json, calls = parse_cromwell_metadata_json_file(args.metadata_json_file)
  File "/home/users/annashch/chip-seq-pipeline2/utils/resumer/resumer.py", line 44, in parse_cromwell_metadata_json_file
    org_input_json = json.loads(metadata_json['submittedFiles']['inputs'], object_pairs_hook=OrderedDict)
  File "/scratch/users/annashch/miniconda3/lib/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/scratch/users/annashch/miniconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/scratch/users/annashch/miniconda3/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 9 column 1 (char 1168)

```

**Comment by leepc12** [comment]
Resumer has beed deprecated.
