### ISSUE TITLE
Error with Chip-Seq Singularity Pipeline at Macs2 Peak Calling

### ISSUE THREAD

**Issue by tiagobrc** [ENCODE-DCC/chip-seq-pipeline2#71]
During MACS2 processing with Singularity Chip-Seq pipeline, the pipeline throws up an error. I Tried but couldn't identify the origin of the error.

Can you help me? What am I missing?

I appreciate a lot thanks!

```
singularity --version
2.6.1-dist
```

Input.json:
```
{
    "chip.genome_tsv" : "mm10.tsv",
    "chip.paired_end" : false,

    "chip.fastqs_rep1_R1" : [ "ChIP_R1.fastq.gz"],
    "chip.ctl_fastqs_rep1_R1" : [ "ChIP_Input_R1.fastq.gz" ],

    "chip.title" : "ChIP",
    "chip.description" : "ChIP Project",

    "chip.pipeline_type" : "tf",
    "chip.peak_caller" : "spp",

    "chip.align_only" : false,
    "chip.true_rep_only" : false,

    "chip.disable_fingerprint" : false,
    "chip.enable_count_signal_track" : false,

    "chip.xcor_pe_trim_bp" : 50,

    "chip.dup_marker" : "picard",
    "chip.mapq_thresh" : 30,
    "chip.no_dup_removal" : false,

    "chip.mito_chr_name" : "chrM",
    "chip.regex_filter_reads" : "chrM",
    "chip.subsample_reads" : 0,
    "chip.ctl_subsample_reads" : 0,
    "chip.xcor_subsample_reads" : 15000000,

    "chip.keep_irregular_chr_in_bfilt_peak" : false,
    
    "chip.always_use_pooled_ctl" : true,
    "chip.ctl_depth_ratio" : 1.2,

    "chip.macs2_cap_num_peak" : 500000,
    "chip.pval_thresh" : 0.01,
    "chip.idr_thresh" : 0.05,
    "chip.spp_cap_num_peak" : 300000,

    "chip.bwa_cpu" : 12,
    "chip.bwa_mem_mb" : 200000,
    "chip.bwa_time_hr" : 480,
    "chip.bwa_disks" : "local-disk 100 HDD",

    "chip.filter_cpu" : 12,
    "chip.filter_mem_mb" : 20000,
    "chip.filter_time_hr" : 24,
    "chip.filter_disks" : "local-disk 100 HDD",

    "chip.bam2ta_cpu" : 12,
    "chip.bam2ta_mem_mb" : 100000,
    "chip.bam2ta_time_hr" : 6,
    "chip.bam2ta_disks" : "local-disk 100 HDD",

    "chip.spr_mem_mb" : 16000,

    "chip.fingerprint_cpu" : 12,
    "chip.fingerprint_mem_mb" : 12000,
    "chip.fingerprint_time_hr" : 6,
    "chip.fingerprint_disks" : "local-disk 100 HDD",

    "chip.xcor_cpu" : 12,
    "chip.xcor_mem_mb" : 16000,
    "chip.xcor_time_hr" : 24,
    "chip.xcor_disks" : "local-disk 100 HDD",

    "chip.macs2_mem_mb" : 16000,
    "chip.macs2_time_hr" : 24,
    "chip.macs2_disks" : "local-disk 100 HDD",

    "chip.spp_cpu" : 12,
    "chip.spp_mem_mb" : 16000,
    "chip.spp_time_hr" : 72,
    "chip.spp_disks" : "local-disk 100 HDD"
}
```

```
find -name stderr -not -empty | xargs tail -n +1
Traceback (most recent call last):
  File "/software/chip-seq-pipeline/src/encode_macs2_chip.py", line 225, in <module>
    main()
  File "/software/chip-seq-pipeline/src/encode_macs2_chip.py", line 200, in main
    args.out_dir)
  File "/software/chip-seq-pipeline/src/encode_macs2_chip.py", line 88, in macs2
    run_shell_cmd(cmd0)
  File "/software/chip-seq-pipeline/src/encode_common.py", line 252, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=28849, PGID=28849, RC=1
STDERR=ERROR:root:--extsize must >= 1!
STDOUT=

```

**Comment by leepc12** [comment]
It looks like cross-correlation failed to estimate the fragment length of your sample. Please check your samples' quality or try with manually defined fragment length in your input JSON file.

For example of two replicates,
```
{
...
    "chip.fraglen" = [200, 150]
...
}
```

**Comment by tiagobrc** [comment]
I got an error while using this parameters on the json file:


`Unexpected character '=' at input index 1013 (line 37, position 20), expected ':':
    "chip.fraglen" = [51, 51],`

**Comment by tiagobrc** [comment]
Hi Thanks for the response. I put this information on the input.json but it didn't work. It broke right after the beginning. Am I missing something?

```
[2019-05-22 16:38:47,62] [info] PAPIQueryManager Running with 3 workers
[2019-05-22 16:38:47,70] [info] MaterializeWorkflowDescriptorActor [d410b2bb]: Parsing workflow as WDL draft-2
[2019-05-22 16:38:51,32] [error] WorkflowManagerActor Workflow d410b2bb-b0c9-4bbb-a286-a4b725b13e5b failed (during Materializi
ngWorkflowDescriptorState): cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anon$1: Wor
kflow input processing failed:
Unexpected character '=' at input index 2012 (line 72, position 20), expected ':':
    "chip.fraglen" = [200, 150],
                   ^

        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.cromwell$engine$workflow$life
cycle$materialization$MaterializeWorkflowDescriptorActor$$workflowInitializationFailed(MaterializeWorkflowDescriptorActor.scal
a:215)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(Materi
alizeWorkflowDescriptorActor.scala:185)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(Materi
alizeWorkflowDescriptorActor.scala:180)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
        at akka.actor.FSM.processEvent(FSM.scala:684)
        at akka.actor.FSM.processEvent$(FSM.scala:681)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.akka$actor$LoggingFSM$$super$
processEvent(MaterializeWorkflowDescriptorActor.scala:136)
        at akka.actor.LoggingFSM.processEvent(FSM.scala:820)
        at akka.actor.LoggingFSM.processEvent$(FSM.scala:802)
```


Thanks!

**Comment by leepc12** [comment]
Use : instead of =

"chip.fraglen": [200, 150],

**Comment by tiagobrc** [comment]
It worked now. Thanks! Question : can the chip pipeline run without the input of the  sample?

Thanks!

**Comment by leepc12** [comment]
@tiagobrc : TF ChIP-seq cannot run without inputs but histone ChIP-seq can do .
