### ISSUE TITLE
IDR-related issue on histone pipeline

### ISSUE THREAD

**Issue by amulyagarimella** [ENCODE-DCC/chip-seq-pipeline2#78]
I'm having a persistent issue that seems to be related to IDR. I'm running the pipeline on a SLURM cluster with Conda version 4.6.14 and cromwell-38. I am also running the pipeline for histone ChIP-seq, so I'm not supposed to be finding IDR. To try and fix this, I disabled IDR in my chip.wdl file, but still got the error.
I attached the debug.tar.gz file below. Thanks!

**Error Log:**
```
Traceback (most recent call last):
  File "/home/amulyag/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_idr.py", line 169, in <module>
    main()
  File "/home/amulyag/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_idr.py", line 137, in main
    args.idr_thresh, args.idr_rank, args.out_dir)
  File "/home/amulyag/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_idr.py", line 93, in idr
    run_shell_cmd(cmd1)
  File "/home/amulyag/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_common.py", line 252, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=73703, PGID=73703, RC=127
STDERR=/bin/bash: line 1: idr: command not found
STDOUT=
```

[debug.tar.gz](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/3356742/debug.tar.gz)

**Comment by amulyagarimella** [comment]
I found that there is an instance where IDR is called despite enable_idr being set to false. On [line 1059](https://github.com/ENCODE-DCC/chip-seq-pipeline2/blob/844bec3da934a7ede297b56f2034649f4f59daaf/chip.wdl#L1059), IDR is called regardless of enable_idr. When I added enable_idr as a condition, I got a different error (see #79).

**Comment by leepc12** [comment]
Unlike ATAC-Seq pipeline, `enable_idr` is not a parameter for ChIP-Seq. It's automatically enables for TF and disabled for histone.

**Comment by leepc12** [comment]
It looks like your python3 conda environment was not installed correctly. Pipeline installs two envs (encode-chip-seq-pipeline, encode-chip-seq-pipeline-python3). Reinstall conda envs and check if the following works.
```
$ source activate encode-chip-seq-pipeline
$ which idr
```

**Comment by amulyagarimella** [comment]
The environments appeared to install correctly, but `which idr` did not seem to work. This is the error I got:
`/usr/bin/which: no idr in (/home/amulyag/miniconda3/envs/encode-chip-seq-pipeline/bin:/home/amulyag/miniconda3/bin:/home/amulyag/miniconda3/bin:/home/amulyag/miniconda3/condabin:/opt/openmpi/bin:/usr/lib64/qt-3.3/bin:/opt/maui/bin:/opt/torque/bin:/opt/torque/sbin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/bio/ncbi/bin:/opt/bio/mpiblast/bin:/opt/bio/EMBOSS/bin:/opt/bio/clustalw/bin:/opt/bio/tcoffee/bin:/opt/bio/hmmer/bin:/opt/bio/phylip/exe:/opt/bio/mrbayes:/opt/bio/fasta:/opt/bio/glimmer/bin:/opt/bio/glimmer/scripts:/opt/bio/gromacs/bin:/opt/bio/gmap/bin:/opt/bio/tigr/bin:/opt/bio/autodocksuite/bin:/opt/bio/wgs/bin:/opt/ganglia/bin:/opt/ganglia/sbin:/usr/java/latest/bin:/opt/pdsh/bin:/opt/rocks/bin:/opt/rocks/sbin:/home/amulyag/bin)`

**Comment by leepc12** [comment]
Did you run `conda/config_conda_env.sh` after installing dependencies?

https://github.com/ENCODE-DCC/chip-seq-pipeline2/blob/master/conda/config_conda_env.sh#L57

**Comment by amulyagarimella** [comment]
I reinstalled and configured my conda environments, and got a result for `which idr`. I re-ran the pipeline and got the following error:

```
[2019-07-09 12:09:20,08] [ESC[38;5;1merrorESC[0m] WorkflowManagerActor Workflow 0236f082-7cb4-4c25-a381-b99237345738 failed (during E
xecutingWorkflowState): cromwell.engine.workflow.lifecycle.execution.job.preparation.JobPreparationActor$$anonfun$1$$anon$1: Call inp
ut and runtime attributes evaluation failed for qc_report:
Failed to evaluate input 'jsd_qcs' (reason 1 of 1): Failed to lookup input value for required input jsd_qcs
        at cromwell.engine.workflow.lifecycle.execution.job.preparation.JobPreparationActor$$anonfun$1.applyOrElse(JobPreparationActo
r.scala:70)
        at cromwell.engine.workflow.lifecycle.execution.job.preparation.JobPreparationActor$$anonfun$1.applyOrElse(JobPreparationActo
r.scala:66)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
        at akka.actor.FSM.processEvent(FSM.scala:684)
        at akka.actor.FSM.processEvent$(FSM.scala:681)
        at cromwell.engine.workflow.lifecycle.execution.job.preparation.JobPreparationActor.processEvent(JobPreparationActor.scala:42
)
        at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:678)
        at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:672)
        at akka.actor.Actor.aroundReceive(Actor.scala:517)
        at akka.actor.Actor.aroundReceive$(Actor.scala:515)
        at cromwell.engine.workflow.lifecycle.execution.job.preparation.JobPreparationActor.aroundReceive(JobPreparationActor.scala:4
2)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
        at akka.actor.ActorCell.invoke(ActorCell.scala:557)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
        at akka.dispatch.Mailbox.run(Mailbox.scala:225)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

I think this is the same error described in issue #79. Thanks for helping me out with the IDR error!
