### ISSUE TITLE
JSD-related error on conda pipeline for histone ChIP-seq

### ISSUE THREAD

**Issue by amulyagarimella** [ENCODE-DCC/chip-seq-pipeline2#79]
I'm having a persistent JSD-related error. I'm running the pipeline on a SLURM cluster with Conda version 4.6.14 and cromwell-38. I have no control data so it seems like I can't create a JSD plot. I disabled JSD, but the error persists. Also, this error began to occur when I disabled all instances where IDR was called in an attempt to fix issue #78.

**Error Logs**
```
cromwell.engine.workflow.lifecycle.execution.job.preparation.JobPreparationActor$$anonfun$1$$anon$1: Call inp
ut and runtime attributes evaluation failed for qc_report:
Failed to evaluate input 'jsd_qcs' (reason 1 of 1): Failed to lookup input value for required input jsd_qcs
        at cromwell.engine.workflow.lifecycle.execution.job.preparation.JobPreparationActor$$anonfun$1.applyOrElse(JobPreparationActo
r.scala:70)
        at cromwell.engine.workflow.lifecycle.execution.job.preparation.JobPreparationActor$$anonfun$1.applyOrElse(JobPreparationActo
r.scala:66)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
        at akka.actor.FSM.processEvent(FSM.scala:684)
        at akka.actor.FSM.processEvent$(FSM.scala:681)
        at cromwell.engine.workflow.lifecycle.execution.job.preparation.JobPreparationActor.processEvent(JobPreparationActor.scala:42
)
        at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:678)
        at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:672)
        at akka.actor.Actor.aroundReceive(Actor.scala:517)
        at akka.actor.Actor.aroundReceive$(Actor.scala:515)
        at cromwell.engine.workflow.lifecycle.execution.job.preparation.JobPreparationActor.aroundReceive(JobPreparationActor.scala:4
2)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
        at akka.actor.ActorCell.invoke(ActorCell.scala:557)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
        at akka.dispatch.Mailbox.run(Mailbox.scala:225)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
This didn't show up in stderr, but the workflow failed when I got this error.

[debug_79.tar.gz](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/3370290/debug_79.tar.gz)

**Comment by amulyagarimella** [comment]
I tried to run the pipeline again with some changes (reconfigured the conda environment and used default .wdl file). I got the same error. It's still not showing up in stderr. I've attached the debug file below.

**Error Logs**
```
WorkflowManagerActor Workflow 0236f082-7cb4-4c25-a381-b99237345738 failed (during E
xecutingWorkflowState): cromwell.engine.workflow.lifecycle.execution.job.preparation.JobPreparationActor$$anonfun$1$$anon$1: Call inp
ut and runtime attributes evaluation failed for qc_report:
Failed to evaluate input 'jsd_qcs' (reason 1 of 1): Failed to lookup input value for required input jsd_qcs
        at cromwell.engine.workflow.lifecycle.execution.job.preparation.JobPreparationActor$$anonfun$1.applyOrElse(JobPreparationActo
r.scala:70)
        at cromwell.engine.workflow.lifecycle.execution.job.preparation.JobPreparationActor$$anonfun$1.applyOrElse(JobPreparationActo
r.scala:66)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
        at akka.actor.FSM.processEvent(FSM.scala:684)
        at akka.actor.FSM.processEvent$(FSM.scala:681)
        at cromwell.engine.workflow.lifecycle.execution.job.preparation.JobPreparationActor.processEvent(JobPreparationActor.scala:42
)
        at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:678)
        at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:672)
        at akka.actor.Actor.aroundReceive(Actor.scala:517)
        at akka.actor.Actor.aroundReceive$(Actor.scala:515)
        at cromwell.engine.workflow.lifecycle.execution.job.preparation.JobPreparationActor.aroundReceive(JobPreparationActor.scala:4
2)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
        at akka.actor.ActorCell.invoke(ActorCell.scala:557)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
        at akka.dispatch.Mailbox.run(Mailbox.scala:225)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
[debug_79.tar.gz](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/3374106/debug_79.tar.gz)

**Comment by amulyagarimella** [comment]
I also wanted to add that I don't have a control input — I think that might be related to the JSD issue.

**Comment by leepc12** [comment]
This will be fixed in the next release. Until then you can simply fix it by editing https://github.com/ENCODE-DCC/chip-seq-pipeline2/blob/master/chip.wdl#L1759

Replace
```
Array[File?] jsd_qcs
```
with
```
Array[File]? jsd_qcs
```

**Comment by amulyagarimella** [comment]
This worked! Thanks so much for your help!

**Comment by guma44** [comment]
Hi,

Was this fixed actually? I see the line:
```
Array[File?] jsd_qcs
```
Is still there in the newest release and I am experiencing this error. I will try to correct the line and see if it is gone.

**Comment by leepc12** [comment]
There has been no release since then. It is already fixed in the dev version (next release).

**Comment by guma44** [comment]
Thanks, so I fixed it manually and when the new version is available I will install it then.
