### ISSUE TITLE
call-qc-report fails with unequal number of samples and inputs

### ISSUE THREAD

**Issue by mperalc** [ENCODE-DCC/chip-seq-pipeline2#83]
Hello,

The pipeline runs well with 3 replicates of sample and input files, but fails at the call-qc report step in runs with 2 replicates of sample and 3 of input.

**OS/Platform and dependencies**
- CentOS release 6.8
- Conda version 4.7.10
- Caper version 0.3.15

**Error logs**
```
Found failures:
[
    {
        "message": "Workflow failed",
        "causedBy": [
            {
                "message": "Job chip.qc_report:NA:2 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.",
                "causedBy": []
            }
        ]
    }
]

chip.qc_report RetryableFailure. SHARD_IDX=-1, RC=1, JOB_ID=96011, RUN_START=2019-08-05T17:44:38.559Z, RUN_END=2019-08-05T17:44:53.501Z, STDOUT=/gpfs2/well/mccarthy/production/chip-seq/data/Islet_diff_2016/merged/trimmed/BLC/chip/5ece5f92-6320-459b-90b6-d522fc61871f/call-qc_report/execution/stdout, STDERR=/gpfs2/well/mccarthy/production/chip-seq/data/Islet_diff_2016/merged/trimmed/BLC/chip/5ece5f92-6320-459b-90b6-d522fc61871f/call-qc_report/execution/stderr
STDERR_CONTENTS=
Traceback (most recent call last):
  File "/well/mccarthy/production/chip-seq/dependencies/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_qc_report.py", line 633, in <module>
    main()
  File "/well/mccarthy/production/chip-seq/dependencies/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_qc_report.py", line 301, in main
    row_header.extend(get_ctl_labels(json_objs, args.ctl_paired_ends))
  File "/well/mccarthy/production/chip-seq/dependencies/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_qc_report.py", line 244, in get_ctl_labels
    if paired_ends[i]:
IndexError: list index out of range


chip.qc_report Failed. SHARD_IDX=-1, RC=1, JOB_ID=96048, RUN_START=2019-08-05T17:44:54.555Z, RUN_END=2019-08-05T17:45:07.690Z, STDOUT=/gpfs2/well/mccarthy/production/chip-seq/data/Islet_diff_2016/merged/trimmed/BLC/chip/5ece5f92-6320-459b-90b6-d522fc61871f/call-qc_report/attempt-2/execution/stdout, STDERR=/gpfs2/well/mccarthy/production/chip-seq/data/Islet_diff_2016/merged/trimmed/BLC/chip/5ece5f92-6320-459b-90b6-d522fc61871f/call-qc_report/attempt-2/execution/stderr
STDERR_CONTENTS=
Traceback (most recent call last):
  File "/well/mccarthy/production/chip-seq/dependencies/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_qc_report.py", line 633, in <module>
    main()
  File "/well/mccarthy/production/chip-seq/dependencies/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_qc_report.py", line 301, in main
    row_header.extend(get_ctl_labels(json_objs, args.ctl_paired_ends))
  File "/well/mccarthy/production/chip-seq/dependencies/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_qc_report.py", line 244, in get_ctl_labels
    if paired_ends[i]:
IndexError: list index out of range
```
Thank you for your work and your help.
Attached are the log tar files (the GOOD one is an example of successful run, while the other two threw the error described).
[debug_ISSUE_83_GOOD.tar.gz](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/3479321/debug_ISSUE_83_GOOD.tar.gz)
[debug_ISSUE_83_B.tar.gz](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/3479322/debug_ISSUE_83_B.tar.gz)
[debug_ISSUE_83_A.tar.gz](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/3479323/debug_ISSUE_83_A.tar.gz)

**Comment by leepc12** [comment]
Please upload your input JSON file for failed runs.

**Comment by mperalc** [comment]
Thank you for the prompt reply. Here are the json files.
[JSON.zip](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/3483402/JSON.zip)

**Comment by leepc12** [comment]
@mperalc: We will make a new release soon to fix this. The above workaround will not work.

**Comment by mperalc** [comment]
Thank you very much for your help again. I'll try this now.
